export interface TextOverlay {
  text: string;
  x: number; // percentage 0-100
  y: number; // percentage 0-100
  fontSize: number;
  fontFamily: string;
  fontWeight: string;
  color: string;
}

export interface StoryboardParams {
  theme: string;
  audience: 'middle-school' | 'high-school' | 'college' | 'teacher' | 'general';
  tone: 'educational' | 'serious' | 'encouraging' | 'critical';
  panelCount: 3 | 4 | 5 | 6;
  aspectRatio: '1:1' | '4:3' | '3:4' | '16:9';
  language: 'zh' | 'en';
  colorScheme: 'soft' | 'high-contrast';
  textDensity: 'low' | 'medium' | 'high';
}

export interface StoryboardResult {
  id: string;
  params: StoryboardParams;
  imageUrl: string;
  prompt: string;
  createdAt: string;
  keywords?: TextOverlay[];
}

export const DEFAULT_PARAMS: StoryboardParams = {
  theme: '',
  audience: 'college',
  tone: 'educational',
  panelCount: 4,
  aspectRatio: '4:3',
  language: 'zh',
  colorScheme: 'soft',
  textDensity: 'medium',
};

// Helper functions for keyword styling presets
const title = (text: string, x: number, y: number, color = '#2c3e50'): TextOverlay => ({
  text, x, y, fontSize: 32, fontFamily: 'ZCOOL KuaiLe', fontWeight: '700', color,
});

const subtitle = (text: string, x: number, y: number, color = '#34495e'): TextOverlay => ({
  text, x, y, fontSize: 20, fontFamily: 'Noto Sans SC', fontWeight: '600', color,
});

const label = (text: string, x: number, y: number, color = '#7f8c8d'): TextOverlay => ({
  text, x, y, fontSize: 14, fontFamily: 'Noto Sans SC', fontWeight: '400', color,
});

const accent = (text: string, x: number, y: number, color = '#e74c3c'): TextOverlay => ({
  text, x, y, fontSize: 18, fontFamily: 'Ma Shan Zheng', fontWeight: '500', color,
});

export type TemplateCategory = 'teaching' | 'thinking' | 'learning' | 'analysis' | 'creative' | 'goals' | 'compare' | 'special';

export const TEMPLATE_CATEGORIES: { key: TemplateCategory; nameKey: string }[] = [
  { key: 'teaching', nameKey: 'storyboard.category.teaching' },
  { key: 'thinking', nameKey: 'storyboard.category.thinking' },
  { key: 'learning', nameKey: 'storyboard.category.learning' },
  { key: 'analysis', nameKey: 'storyboard.category.analysis' },
  { key: 'creative', nameKey: 'storyboard.category.creative' },
  { key: 'goals', nameKey: 'storyboard.category.goals' },
  { key: 'compare', nameKey: 'storyboard.category.compare' },
  { key: 'special', nameKey: 'storyboard.category.special' },
];

export interface TemplateConfig {
  name: string;
  nameKey: string;
  category: TemplateCategory;
  params: Partial<StoryboardParams>;
  keywords: TextOverlay[];
}

export const TEMPLATES: TemplateConfig[] = [
  // 教学流程类
  {
    name: '五问反思',
    nameKey: 'storyboard.template.fiveWhys',
    category: 'teaching',
    params: {
      theme: '五问反思法：为什么学习AI？为什么需要批判思维？为什么要验证信息？为什么要负责任地使用？为什么要持续学习？',
      audience: 'college',
      tone: 'critical',
      panelCount: 5,
      textDensity: 'medium',
    },
    keywords: [
      title('五问反思法', 50, 8, '#8e44ad'),
      subtitle('Why 1', 10, 28, '#9b59b6'),
      subtitle('Why 2', 30, 28, '#9b59b6'),
      subtitle('Why 3', 50, 28, '#9b59b6'),
      subtitle('Why 4', 70, 28, '#9b59b6'),
      subtitle('Why 5', 90, 28, '#9b59b6'),
      label('深入追问本质', 50, 92, '#7f8c8d'),
    ],
  },
  {
    name: '课堂流程图',
    nameKey: 'storyboard.template.classFlow',
    category: 'teaching',
    params: {
      theme: '一节AI素养课的流程：导入→概念讲解→案例分析→小组讨论→实践练习→总结反思',
      audience: 'teacher',
      tone: 'educational',
      panelCount: 6,
      textDensity: 'high',
    },
    keywords: [
      title('课堂流程', 50, 6, '#2980b9'),
      label('导入', 8, 25, '#3498db'),
      label('讲解', 25, 25, '#3498db'),
      label('案例', 42, 25, '#3498db'),
      label('讨论', 58, 25, '#3498db'),
      label('练习', 75, 25, '#3498db'),
      label('反思', 92, 25, '#3498db'),
      accent('→', 16, 25, '#95a5a6'),
      accent('→', 33, 25, '#95a5a6'),
      accent('→', 50, 25, '#95a5a6'),
      accent('→', 66, 25, '#95a5a6'),
      accent('→', 83, 25, '#95a5a6'),
    ],
  },
  {
    name: '角色对比图',
    nameKey: 'storyboard.template.roleCompare',
    category: 'teaching',
    params: {
      theme: 'AI时代的学生角色转变：被动接收者vs主动探索者，死记硬背vs批判思考，单独学习vs协作创新',
      audience: 'college',
      tone: 'encouraging',
      panelCount: 4,
      textDensity: 'medium',
    },
    keywords: [
      title('角色转变', 50, 8, '#16a085'),
      subtitle('传统模式', 25, 25, '#e74c3c'),
      subtitle('AI时代', 75, 25, '#27ae60'),
      accent('VS', 50, 50, '#f39c12'),
      label('被动 → 主动', 50, 75, '#7f8c8d'),
    ],
  },
  {
    name: '案例分析板',
    nameKey: 'storyboard.template.caseAnalysis',
    category: 'teaching',
    params: {
      theme: 'AI辅助学习的正确打开方式：场景展示→问题分析→解决方案→注意事项',
      audience: 'high-school',
      tone: 'educational',
      panelCount: 4,
      textDensity: 'medium',
    },
    keywords: [
      title('案例分析', 50, 8, '#e67e22'),
      subtitle('场景', 12, 30, '#d35400'),
      subtitle('问题', 37, 30, '#d35400'),
      subtitle('方案', 62, 30, '#d35400'),
      subtitle('注意', 87, 30, '#d35400'),
    ],
  },
  // 思维工具类
  {
    name: '思维导图',
    nameKey: 'storyboard.template.mindMap',
    category: 'thinking',
    params: {
      theme: '中心主题放射状展开：核心概念在中央，四周分支展示关键要点、子主题和细节，用线条连接表示关系',
      audience: 'general',
      tone: 'educational',
      panelCount: 4,
      textDensity: 'medium',
    },
    keywords: [
      title('思维导图', 50, 8, '#9b59b6'),
      { text: '核心主题', x: 50, y: 50, fontSize: 24, fontFamily: 'ZCOOL KuaiLe', fontWeight: '700', color: '#8e44ad' },
      subtitle('分支1', 20, 30, '#3498db'),
      subtitle('分支2', 80, 30, '#e74c3c'),
      subtitle('分支3', 20, 70, '#27ae60'),
      subtitle('分支4', 80, 70, '#f39c12'),
    ],
  },
  {
    name: '时间线',
    nameKey: 'storyboard.template.timeline',
    category: 'thinking',
    params: {
      theme: '横向时间轴展示事件发展：起点→关键节点1→关键节点2→关键节点3→当前状态→未来展望',
      audience: 'general',
      tone: 'educational',
      panelCount: 6,
      textDensity: 'medium',
    },
    keywords: [
      title('时间线', 50, 8, '#2c3e50'),
      label('起点', 8, 50, '#95a5a6'),
      label('节点1', 25, 50, '#3498db'),
      label('节点2', 42, 50, '#3498db'),
      label('节点3', 58, 50, '#3498db'),
      label('现在', 75, 50, '#e74c3c'),
      label('未来', 92, 50, '#27ae60'),
      { text: '●', x: 8, y: 42, fontSize: 16, fontFamily: 'sans-serif', fontWeight: '400', color: '#95a5a6' },
      { text: '●', x: 25, y: 42, fontSize: 16, fontFamily: 'sans-serif', fontWeight: '400', color: '#3498db' },
      { text: '●', x: 42, y: 42, fontSize: 16, fontFamily: 'sans-serif', fontWeight: '400', color: '#3498db' },
      { text: '●', x: 58, y: 42, fontSize: 16, fontFamily: 'sans-serif', fontWeight: '400', color: '#3498db' },
      { text: '●', x: 75, y: 42, fontSize: 16, fontFamily: 'sans-serif', fontWeight: '400', color: '#e74c3c' },
      { text: '●', x: 92, y: 42, fontSize: 16, fontFamily: 'sans-serif', fontWeight: '400', color: '#27ae60' },
    ],
  },
  {
    name: 'SWOT分析',
    nameKey: 'storyboard.template.swot',
    category: 'thinking',
    params: {
      theme: 'SWOT战略分析框架：优势(Strengths)、劣势(Weaknesses)、机会(Opportunities)、威胁(Threats)四象限分析',
      audience: 'college',
      tone: 'serious',
      panelCount: 4,
      textDensity: 'high',
    },
    keywords: [
      title('SWOT 分析', 50, 8, '#2c3e50'),
      subtitle('S 优势', 25, 28, '#27ae60'),
      subtitle('W 劣势', 75, 28, '#e74c3c'),
      subtitle('O 机会', 25, 72, '#3498db'),
      subtitle('T 威胁', 75, 72, '#f39c12'),
      label('Strengths', 25, 36, '#27ae60'),
      label('Weaknesses', 75, 36, '#e74c3c'),
      label('Opportunities', 25, 80, '#3498db'),
      label('Threats', 75, 80, '#f39c12'),
    ],
  },
  {
    name: '鱼骨图',
    nameKey: 'storyboard.template.fishbone',
    category: 'thinking',
    params: {
      theme: '因果分析鱼骨图：主干表示问题结果，鱼骨分支展示人员、方法、材料、设备、环境等原因类别',
      audience: 'college',
      tone: 'serious',
      panelCount: 4,
      textDensity: 'high',
    },
    keywords: [
      title('鱼骨图分析', 50, 8, '#34495e'),
      { text: '问题', x: 90, y: 50, fontSize: 22, fontFamily: 'ZCOOL KuaiLe', fontWeight: '700', color: '#e74c3c' },
      subtitle('人员', 20, 25, '#3498db'),
      subtitle('方法', 40, 25, '#9b59b6'),
      subtitle('材料', 60, 25, '#e67e22'),
      subtitle('设备', 20, 75, '#27ae60'),
      subtitle('环境', 40, 75, '#1abc9c'),
      subtitle('其他', 60, 75, '#95a5a6'),
    ],
  },
  {
    name: '流程图',
    nameKey: 'storyboard.template.flowchart',
    category: 'thinking',
    params: {
      theme: '标准流程图：开始→输入→处理步骤→判断分支→输出→结束，包含循环和条件判断',
      audience: 'general',
      tone: 'educational',
      panelCount: 6,
      textDensity: 'medium',
    },
    keywords: [
      title('流程图', 50, 6, '#2980b9'),
      label('开始', 10, 30, '#27ae60'),
      label('输入', 25, 30, '#3498db'),
      label('处理', 42, 30, '#9b59b6'),
      label('判断', 58, 30, '#f39c12'),
      label('输出', 75, 30, '#3498db'),
      label('结束', 90, 30, '#e74c3c'),
      accent('⬇', 42, 55, '#95a5a6'),
      label('是/否', 58, 45, '#7f8c8d'),
    ],
  },
  {
    name: '金字塔结构',
    nameKey: 'storyboard.template.pyramid',
    category: 'thinking',
    params: {
      theme: '金字塔层级结构：顶层核心观点，中层支撑论据，底层具体事实和数据',
      audience: 'college',
      tone: 'serious',
      panelCount: 3,
      textDensity: 'medium',
    },
    keywords: [
      title('金字塔结构', 50, 8, '#8e44ad'),
      subtitle('核心观点', 50, 25, '#9b59b6'),
      subtitle('支撑论据', 50, 50, '#3498db'),
      subtitle('事实数据', 50, 75, '#27ae60'),
      label('▲', 50, 18, '#9b59b6'),
    ],
  },
  // 学习方法类
  {
    name: 'KWL学习法',
    nameKey: 'storyboard.template.kwl',
    category: 'learning',
    params: {
      theme: 'KWL学习策略：K-我已知道什么(Know)，W-我想学什么(Want)，L-我学到了什么(Learned)',
      audience: 'middle-school',
      tone: 'encouraging',
      panelCount: 3,
      textDensity: 'medium',
    },
    keywords: [
      title('KWL 学习法', 50, 8, '#16a085'),
      subtitle('K 已知', 17, 30, '#3498db'),
      subtitle('W 想学', 50, 30, '#e67e22'),
      subtitle('L 学到', 83, 30, '#27ae60'),
      label('Know', 17, 40, '#3498db'),
      label('Want', 50, 40, '#e67e22'),
      label('Learned', 83, 40, '#27ae60'),
    ],
  },
  {
    name: '费曼学习法',
    nameKey: 'storyboard.template.feynman',
    category: 'learning',
    params: {
      theme: '费曼学习法四步骤：选择概念→教给小白→发现盲点→简化重述',
      audience: 'college',
      tone: 'educational',
      panelCount: 4,
      textDensity: 'medium',
    },
    keywords: [
      title('费曼学习法', 50, 8, '#e74c3c'),
      subtitle('1. 选择概念', 12, 30, '#c0392b'),
      subtitle('2. 教给小白', 37, 30, '#e67e22'),
      subtitle('3. 发现盲点', 62, 30, '#f39c12'),
      subtitle('4. 简化重述', 87, 30, '#27ae60'),
      label('Feynman Technique', 50, 92, '#95a5a6'),
    ],
  },
  {
    name: 'PBL项目学习',
    nameKey: 'storyboard.template.pbl',
    category: 'learning',
    params: {
      theme: '项目式学习流程：提出驱动问题→调研探究→设计方案→制作原型→展示成果→反思改进',
      audience: 'high-school',
      tone: 'encouraging',
      panelCount: 6,
      textDensity: 'medium',
    },
    keywords: [
      title('PBL 项目学习', 50, 6, '#2980b9'),
      label('问题', 8, 28, '#e74c3c'),
      label('调研', 25, 28, '#e67e22'),
      label('设计', 42, 28, '#f1c40f'),
      label('原型', 58, 28, '#27ae60'),
      label('展示', 75, 28, '#3498db'),
      label('反思', 92, 28, '#9b59b6'),
      { text: '1', x: 8, y: 38, fontSize: 12, fontFamily: 'sans-serif', fontWeight: '700', color: '#e74c3c' },
      { text: '2', x: 25, y: 38, fontSize: 12, fontFamily: 'sans-serif', fontWeight: '700', color: '#e67e22' },
      { text: '3', x: 42, y: 38, fontSize: 12, fontFamily: 'sans-serif', fontWeight: '700', color: '#f1c40f' },
      { text: '4', x: 58, y: 38, fontSize: 12, fontFamily: 'sans-serif', fontWeight: '700', color: '#27ae60' },
      { text: '5', x: 75, y: 38, fontSize: 12, fontFamily: 'sans-serif', fontWeight: '700', color: '#3498db' },
      { text: '6', x: 92, y: 38, fontSize: 12, fontFamily: 'sans-serif', fontWeight: '700', color: '#9b59b6' },
    ],
  },
  {
    name: '康奈尔笔记法',
    nameKey: 'storyboard.template.cornell',
    category: 'learning',
    params: {
      theme: '康奈尔笔记系统：左栏关键词/问题，右栏详细笔记，底部总结要点',
      audience: 'college',
      tone: 'educational',
      panelCount: 3,
      textDensity: 'high',
    },
    keywords: [
      title('康奈尔笔记法', 50, 6, '#34495e'),
      subtitle('关键词/问题', 15, 25, '#e74c3c'),
      subtitle('详细笔记', 60, 25, '#3498db'),
      subtitle('总结要点', 50, 85, '#27ae60'),
      label('Cue Column', 15, 33, '#95a5a6'),
      label('Note-Taking Area', 60, 33, '#95a5a6'),
      label('Summary', 50, 92, '#95a5a6'),
    ],
  },
  {
    name: '番茄工作法',
    nameKey: 'storyboard.template.pomodoro',
    category: 'learning',
    params: {
      theme: '番茄工作法：25分钟专注→5分钟休息→循环4次→长休息15-30分钟',
      audience: 'general',
      tone: 'encouraging',
      panelCount: 4,
      textDensity: 'low',
    },
    keywords: [
      title('番茄工作法', 50, 8, '#e74c3c'),
      { text: '🍅', x: 50, y: 22, fontSize: 36, fontFamily: 'sans-serif', fontWeight: '400', color: '#e74c3c' },
      subtitle('25分钟', 20, 50, '#c0392b'),
      subtitle('5分钟', 45, 50, '#27ae60'),
      subtitle('×4', 65, 50, '#3498db'),
      subtitle('长休息', 85, 50, '#9b59b6'),
      label('专注', 20, 60, '#95a5a6'),
      label('休息', 45, 60, '#95a5a6'),
      label('循环', 65, 60, '#95a5a6'),
      label('15-30min', 85, 60, '#95a5a6'),
    ],
  },
  // 分析框架类
  {
    name: 'PEST分析',
    nameKey: 'storyboard.template.pest',
    category: 'analysis',
    params: {
      theme: 'PEST宏观环境分析：政治(Political)、经济(Economic)、社会(Social)、技术(Technological)四维度',
      audience: 'college',
      tone: 'serious',
      panelCount: 4,
      textDensity: 'high',
    },
    keywords: [
      title('PEST 分析', 50, 8, '#2c3e50'),
      subtitle('P 政治', 25, 30, '#e74c3c'),
      subtitle('E 经济', 75, 30, '#27ae60'),
      subtitle('S 社会', 25, 70, '#3498db'),
      subtitle('T 技术', 75, 70, '#f39c12'),
      label('Political', 25, 40, '#e74c3c'),
      label('Economic', 75, 40, '#27ae60'),
      label('Social', 25, 80, '#3498db'),
      label('Technological', 75, 80, '#f39c12'),
    ],
  },
  {
    name: '5W1H分析',
    nameKey: 'storyboard.template.5w1h',
    category: 'analysis',
    params: {
      theme: '5W1H问题分析法：What什么、Why为什么、Who谁、When何时、Where何地、How如何',
      audience: 'general',
      tone: 'educational',
      panelCount: 6,
      textDensity: 'medium',
    },
    keywords: [
      title('5W1H 分析法', 50, 6, '#8e44ad'),
      subtitle('What', 8, 30, '#e74c3c'),
      subtitle('Why', 25, 30, '#e67e22'),
      subtitle('Who', 42, 30, '#f1c40f'),
      subtitle('When', 58, 30, '#27ae60'),
      subtitle('Where', 75, 30, '#3498db'),
      subtitle('How', 92, 30, '#9b59b6'),
      label('什么', 8, 42, '#95a5a6'),
      label('为什么', 25, 42, '#95a5a6'),
      label('谁', 42, 42, '#95a5a6'),
      label('何时', 58, 42, '#95a5a6'),
      label('何地', 75, 42, '#95a5a6'),
      label('如何', 92, 42, '#95a5a6'),
    ],
  },
  {
    name: 'PDCA循环',
    nameKey: 'storyboard.template.pdca',
    category: 'analysis',
    params: {
      theme: 'PDCA持续改进循环：计划(Plan)→执行(Do)→检查(Check)→行动(Act)→再计划',
      audience: 'college',
      tone: 'serious',
      panelCount: 4,
      textDensity: 'medium',
    },
    keywords: [
      title('PDCA 循环', 50, 8, '#2980b9'),
      subtitle('P 计划', 25, 30, '#3498db'),
      subtitle('D 执行', 75, 30, '#27ae60'),
      subtitle('C 检查', 75, 70, '#f39c12'),
      subtitle('A 行动', 25, 70, '#e74c3c'),
      label('Plan', 25, 40, '#3498db'),
      label('Do', 75, 40, '#27ae60'),
      label('Check', 75, 80, '#f39c12'),
      label('Act', 25, 80, '#e74c3c'),
      accent('↻', 50, 50, '#7f8c8d'),
    ],
  },
  {
    name: '优缺点对比',
    nameKey: 'storyboard.template.proscons',
    category: 'analysis',
    params: {
      theme: '优缺点对比分析：左侧列出优点/好处，右侧列出缺点/风险，底部综合评估',
      audience: 'general',
      tone: 'critical',
      panelCount: 3,
      textDensity: 'medium',
    },
    keywords: [
      title('优缺点分析', 50, 8, '#34495e'),
      subtitle('✓ 优点', 25, 28, '#27ae60'),
      subtitle('✗ 缺点', 75, 28, '#e74c3c'),
      label('Pros', 25, 38, '#27ae60'),
      label('Cons', 75, 38, '#e74c3c'),
      subtitle('综合评估', 50, 85, '#3498db'),
    ],
  },
  {
    name: '四象限矩阵',
    nameKey: 'storyboard.template.quadrant',
    category: 'analysis',
    params: {
      theme: '四象限决策矩阵：紧急重要、紧急不重要、不紧急重要、不紧急不重要四个区域',
      audience: 'general',
      tone: 'serious',
      panelCount: 4,
      textDensity: 'medium',
    },
    keywords: [
      title('四象限矩阵', 50, 6, '#2c3e50'),
      subtitle('紧急+重要', 25, 28, '#e74c3c'),
      subtitle('不紧急+重要', 75, 28, '#27ae60'),
      subtitle('紧急+不重要', 25, 72, '#f39c12'),
      subtitle('不紧急+不重要', 75, 72, '#95a5a6'),
      label('立即做', 25, 38, '#e74c3c'),
      label('计划做', 75, 38, '#27ae60'),
      label('委托做', 25, 82, '#f39c12'),
      label('不做', 75, 82, '#95a5a6'),
      accent('重要', 5, 50, '#7f8c8d'),
      accent('紧急', 50, 95, '#7f8c8d'),
    ],
  },
  // 创意设计类
  {
    name: '六顶思考帽',
    nameKey: 'storyboard.template.sixHats',
    category: 'creative',
    params: {
      theme: '六顶思考帽：白帽事实、红帽情感、黑帽批判、黄帽乐观、绿帽创意、蓝帽控制',
      audience: 'college',
      tone: 'critical',
      panelCount: 6,
      textDensity: 'medium',
    },
    keywords: [
      title('六顶思考帽', 50, 6, '#2c3e50'),
      { text: '⬜ 白帽', x: 8, y: 30, fontSize: 16, fontFamily: 'Noto Sans SC', fontWeight: '600', color: '#ecf0f1' },
      { text: '🟥 红帽', x: 25, y: 30, fontSize: 16, fontFamily: 'Noto Sans SC', fontWeight: '600', color: '#e74c3c' },
      { text: '⬛ 黑帽', x: 42, y: 30, fontSize: 16, fontFamily: 'Noto Sans SC', fontWeight: '600', color: '#2c3e50' },
      { text: '🟨 黄帽', x: 58, y: 30, fontSize: 16, fontFamily: 'Noto Sans SC', fontWeight: '600', color: '#f1c40f' },
      { text: '🟩 绿帽', x: 75, y: 30, fontSize: 16, fontFamily: 'Noto Sans SC', fontWeight: '600', color: '#27ae60' },
      { text: '🟦 蓝帽', x: 92, y: 30, fontSize: 16, fontFamily: 'Noto Sans SC', fontWeight: '600', color: '#3498db' },
      label('事实', 8, 42, '#bdc3c7'),
      label('情感', 25, 42, '#e74c3c'),
      label('批判', 42, 42, '#2c3e50'),
      label('乐观', 58, 42, '#f1c40f'),
      label('创意', 75, 42, '#27ae60'),
      label('控制', 92, 42, '#3498db'),
    ],
  },
  {
    name: '设计思维',
    nameKey: 'storyboard.template.designThinking',
    category: 'creative',
    params: {
      theme: '设计思维五阶段：共情(Empathize)→定义(Define)→构思(Ideate)→原型(Prototype)→测试(Test)',
      audience: 'college',
      tone: 'encouraging',
      panelCount: 5,
      textDensity: 'medium',
    },
    keywords: [
      title('Design Thinking', 50, 6, '#9b59b6'),
      subtitle('共情', 10, 30, '#e74c3c'),
      subtitle('定义', 30, 30, '#e67e22'),
      subtitle('构思', 50, 30, '#f1c40f'),
      subtitle('原型', 70, 30, '#27ae60'),
      subtitle('测试', 90, 30, '#3498db'),
      label('Empathize', 10, 42, '#e74c3c'),
      label('Define', 30, 42, '#e67e22'),
      label('Ideate', 50, 42, '#f1c40f'),
      label('Prototype', 70, 42, '#27ae60'),
      label('Test', 90, 42, '#3498db'),
    ],
  },
  {
    name: 'SCAMPER创新',
    nameKey: 'storyboard.template.scamper',
    category: 'creative',
    params: {
      theme: 'SCAMPER创新法：替代、合并、改造、修改、另用、消除、重组七种创新策略',
      audience: 'college',
      tone: 'encouraging',
      panelCount: 4,
      textDensity: 'high',
    },
    keywords: [
      title('SCAMPER', 50, 8, '#e67e22'),
      subtitle('S 替代', 15, 30, '#e74c3c'),
      subtitle('C 合并', 35, 30, '#3498db'),
      subtitle('A 改造', 55, 30, '#27ae60'),
      subtitle('M 修改', 75, 30, '#9b59b6'),
      subtitle('P 另用', 25, 70, '#f1c40f'),
      subtitle('E 消除', 50, 70, '#e67e22'),
      subtitle('R 重组', 75, 70, '#1abc9c'),
    ],
  },
  {
    name: '故事板叙事',
    nameKey: 'storyboard.template.narrative',
    category: 'creative',
    params: {
      theme: '故事叙事结构：开场设置→冲突引入→情节发展→高潮转折→结局收尾',
      audience: 'general',
      tone: 'encouraging',
      panelCount: 5,
      textDensity: 'medium',
    },
    keywords: [
      title('故事叙事', 50, 8, '#8e44ad'),
      subtitle('开场', 10, 30, '#3498db'),
      subtitle('冲突', 30, 30, '#e67e22'),
      subtitle('发展', 50, 30, '#f1c40f'),
      subtitle('高潮', 70, 30, '#e74c3c'),
      subtitle('结局', 90, 30, '#27ae60'),
      label('Setup', 10, 42, '#95a5a6'),
      label('Conflict', 30, 42, '#95a5a6'),
      label('Rising', 50, 42, '#95a5a6'),
      label('Climax', 70, 42, '#95a5a6'),
      label('Resolution', 90, 42, '#95a5a6'),
    ],
  },
  // 目标管理类
  {
    name: 'SMART目标',
    nameKey: 'storyboard.template.smart',
    category: 'goals',
    params: {
      theme: 'SMART目标设定：具体(Specific)、可衡量(Measurable)、可达成(Achievable)、相关性(Relevant)、时限(Time-bound)',
      audience: 'college',
      tone: 'serious',
      panelCount: 5,
      textDensity: 'medium',
    },
    keywords: [
      title('SMART 目标', 50, 8, '#16a085'),
      subtitle('S 具体', 10, 32, '#e74c3c'),
      subtitle('M 可衡量', 30, 32, '#e67e22'),
      subtitle('A 可达成', 50, 32, '#f1c40f'),
      subtitle('R 相关性', 70, 32, '#27ae60'),
      subtitle('T 时限', 90, 32, '#3498db'),
      label('Specific', 10, 44, '#e74c3c'),
      label('Measurable', 30, 44, '#e67e22'),
      label('Achievable', 50, 44, '#f1c40f'),
      label('Relevant', 70, 44, '#27ae60'),
      label('Time-bound', 90, 44, '#3498db'),
    ],
  },
  {
    name: 'OKR目标',
    nameKey: 'storyboard.template.okr',
    category: 'goals',
    params: {
      theme: 'OKR目标管理：设定目标(Objective)→定义关键结果(Key Results)→执行追踪→复盘评估',
      audience: 'college',
      tone: 'serious',
      panelCount: 4,
      textDensity: 'medium',
    },
    keywords: [
      title('OKR 目标管理', 50, 8, '#2980b9'),
      subtitle('O 目标', 20, 30, '#e74c3c'),
      subtitle('KR 关键结果', 50, 30, '#3498db'),
      subtitle('执行追踪', 80, 30, '#27ae60'),
      label('Objective', 20, 42, '#e74c3c'),
      label('Key Results', 50, 42, '#3498db'),
      label('Track & Review', 80, 42, '#27ae60'),
      accent('→', 35, 35, '#95a5a6'),
      accent('→', 65, 35, '#95a5a6'),
    ],
  },
  {
    name: '行动计划表',
    nameKey: 'storyboard.template.actionPlan',
    category: 'goals',
    params: {
      theme: '行动计划模板：目标描述→具体任务→负责人→截止日期→资源需求→进度状态',
      audience: 'teacher',
      tone: 'serious',
      panelCount: 6,
      textDensity: 'high',
    },
    keywords: [
      title('行动计划', 50, 6, '#34495e'),
      subtitle('目标', 8, 28, '#e74c3c'),
      subtitle('任务', 25, 28, '#3498db'),
      subtitle('负责人', 42, 28, '#9b59b6'),
      subtitle('截止', 58, 28, '#e67e22'),
      subtitle('资源', 75, 28, '#27ae60'),
      subtitle('进度', 92, 28, '#1abc9c'),
    ],
  },
  // 对比展示类
  {
    name: '前后对比',
    nameKey: 'storyboard.template.beforeAfter',
    category: 'compare',
    params: {
      theme: '前后对比展示：改变前的状态/问题→转变过程→改变后的效果/成果',
      audience: 'general',
      tone: 'encouraging',
      panelCount: 3,
      textDensity: 'low',
    },
    keywords: [
      title('前后对比', 50, 8, '#2c3e50'),
      subtitle('Before', 17, 30, '#e74c3c'),
      subtitle('转变', 50, 30, '#f39c12'),
      subtitle('After', 83, 30, '#27ae60'),
      label('改变前', 17, 42, '#e74c3c'),
      accent('→', 50, 50, '#f39c12'),
      label('改变后', 83, 42, '#27ae60'),
    ],
  },
  {
    name: '正误对比',
    nameKey: 'storyboard.template.rightWrong',
    category: 'compare',
    params: {
      theme: '正确与错误做法对比：错误示范(打叉)vs正确示范(打勾)，配合说明原因',
      audience: 'middle-school',
      tone: 'educational',
      panelCount: 4,
      textDensity: 'medium',
    },
    keywords: [
      title('正误对比', 50, 8, '#34495e'),
      { text: '✗', x: 25, y: 35, fontSize: 48, fontFamily: 'sans-serif', fontWeight: '700', color: '#e74c3c' },
      { text: '✓', x: 75, y: 35, fontSize: 48, fontFamily: 'sans-serif', fontWeight: '700', color: '#27ae60' },
      subtitle('错误做法', 25, 60, '#e74c3c'),
      subtitle('正确做法', 75, 60, '#27ae60'),
      label('Wrong', 25, 72, '#e74c3c'),
      label('Right', 75, 72, '#27ae60'),
    ],
  },
  {
    name: '步骤指南',
    nameKey: 'storyboard.template.stepGuide',
    category: 'compare',
    params: {
      theme: '分步操作指南：第一步→第二步→第三步→第四步，每步配图说明',
      audience: 'general',
      tone: 'educational',
      panelCount: 4,
      textDensity: 'medium',
    },
    keywords: [
      title('步骤指南', 50, 8, '#2980b9'),
      { text: '①', x: 12, y: 30, fontSize: 28, fontFamily: 'sans-serif', fontWeight: '700', color: '#3498db' },
      { text: '②', x: 37, y: 30, fontSize: 28, fontFamily: 'sans-serif', fontWeight: '700', color: '#3498db' },
      { text: '③', x: 62, y: 30, fontSize: 28, fontFamily: 'sans-serif', fontWeight: '700', color: '#3498db' },
      { text: '④', x: 87, y: 30, fontSize: 28, fontFamily: 'sans-serif', fontWeight: '700', color: '#3498db' },
      label('Step 1', 12, 45, '#95a5a6'),
      label('Step 2', 37, 45, '#95a5a6'),
      label('Step 3', 62, 45, '#95a5a6'),
      label('Step 4', 87, 45, '#95a5a6'),
    ],
  },
  // 特殊用途类
  {
    name: '用户旅程图',
    nameKey: 'storyboard.template.userJourney',
    category: 'special',
    params: {
      theme: '用户体验旅程：意识阶段→考虑阶段→决策阶段→使用阶段→推荐阶段，标注触点和情绪',
      audience: 'college',
      tone: 'serious',
      panelCount: 5,
      textDensity: 'medium',
    },
    keywords: [
      title('用户旅程图', 50, 6, '#9b59b6'),
      subtitle('意识', 10, 30, '#3498db'),
      subtitle('考虑', 30, 30, '#e67e22'),
      subtitle('决策', 50, 30, '#f1c40f'),
      subtitle('使用', 70, 30, '#27ae60'),
      subtitle('推荐', 90, 30, '#e74c3c'),
      label('Awareness', 10, 42, '#95a5a6'),
      label('Consider', 30, 42, '#95a5a6'),
      label('Decision', 50, 42, '#95a5a6'),
      label('Use', 70, 42, '#95a5a6'),
      label('Advocate', 90, 42, '#95a5a6'),
      accent('😐', 10, 75, '#f39c12'),
      accent('🤔', 30, 75, '#e67e22'),
      accent('😊', 50, 75, '#27ae60'),
      accent('😄', 70, 75, '#27ae60'),
      accent('🥰', 90, 75, '#e74c3c'),
    ],
  },
  {
    name: '商业画布',
    nameKey: 'storyboard.template.businessCanvas',
    params: {
      theme: '商业模式画布九要素：价值主张、客户细分、渠道、客户关系、收入来源、核心资源、关键活动、合作伙伴、成本结构',
      audience: 'college',
      tone: 'serious',
      panelCount: 4,
      textDensity: 'high',
    },
    keywords: [
      title('商业画布', 50, 4, '#2c3e50'),
      subtitle('价值主张', 50, 25, '#e74c3c'),
      label('客户细分', 85, 25, '#3498db'),
      label('渠道', 85, 50, '#27ae60'),
      label('客户关系', 85, 75, '#9b59b6'),
      label('收入来源', 70, 90, '#f39c12'),
      label('核心资源', 15, 50, '#1abc9c'),
      label('关键活动', 35, 50, '#e67e22'),
      label('合作伙伴', 15, 25, '#8e44ad'),
      label('成本结构', 30, 90, '#95a5a6'),
    ],
  },
  {
    name: '复盘总结',
    nameKey: 'storyboard.template.retrospective',
    params: {
      theme: '项目复盘四步法：回顾目标→评估结果→分析原因→总结经验',
      audience: 'teacher',
      tone: 'critical',
      panelCount: 4,
      textDensity: 'medium',
    },
    keywords: [
      title('复盘总结', 50, 8, '#8e44ad'),
      subtitle('回顾目标', 12, 32, '#3498db'),
      subtitle('评估结果', 37, 32, '#27ae60'),
      subtitle('分析原因', 62, 32, '#f39c12'),
      subtitle('总结经验', 87, 32, '#e74c3c'),
      label('Goal', 12, 44, '#3498db'),
      label('Result', 37, 44, '#27ae60'),
      label('Analysis', 62, 44, '#f39c12'),
      label('Lessons', 87, 44, '#e74c3c'),
    ],
  },
  {
    name: '知识卡片',
    nameKey: 'storyboard.template.knowledgeCard',
    params: {
      theme: '知识点卡片：核心概念定义→关键特征→实际例子→常见误区',
      audience: 'middle-school',
      tone: 'educational',
      panelCount: 4,
      textDensity: 'medium',
    },
    keywords: [
      title('知识卡片', 50, 8, '#16a085'),
      subtitle('定义', 12, 32, '#e74c3c'),
      subtitle('特征', 37, 32, '#3498db'),
      subtitle('例子', 62, 32, '#27ae60'),
      subtitle('误区', 87, 32, '#f39c12'),
      label('Definition', 12, 44, '#95a5a6'),
      label('Features', 37, 44, '#95a5a6'),
      label('Examples', 62, 44, '#95a5a6'),
      label('Pitfalls', 87, 44, '#95a5a6'),
    ],
  },
];
