project_id = "vtlecaojupfsawcobbid"

[functions.generate-storyboard]
verify_jwt = false

[functions.generate-ppt-outline]
verify_jwt = false

[functions.generate-ppt-image]
verify_jwt = false

[functions.analyze-text]
verify_jwt = false

[functions.analyze-board]
verify_jwt = false

[functions.generate-quiz-questions]
verify_jwt = false

[functions.analyze-barrage]
verify_jwt = false
