import { createContext, useContext, useState, useCallback, ReactNode } from 'react';

export type LangCode = 'zh' | 'en' | 'ru' | 'ja' | 'ko';

export interface LangOption {
  code: LangCode;
  label: string;
  flag: string;
}

export const LANGUAGES: LangOption[] = [
  { code: 'zh', label: '中文', flag: '🇨🇳' },
  { code: 'en', label: 'English', flag: '🇬🇧' },
  { code: 'ru', label: 'Русский', flag: '🇷🇺' },
  { code: 'ja', label: '日本語', flag: '🇯🇵' },
  { code: 'ko', label: '한국어', flag: '🇰🇷' },
];

const translations: Record<LangCode, Record<string, string>> = {
  zh: {
    // App header
    'app.title': '互动课堂派',
    'app.subtitle': 'TeachMate |--洛阳理工学院--| limeng@lit.edu.cn',
    // Tabs
    'tab.random': '随机选人',
    'tab.groups': '分组',
    'tab.teams': '建队',
    'tab.seats': '座位',
    'tab.checkin': '签到',
    'tab.board': '白板',
    'tab.toolkit': '工具箱',
    'tab.quiz': '测验',
    // External links
    'ext.ai': 'AI助手',
    'ext.idea': '思享岛',
    'ext.tip': '与本平台使用同一邮箱即可登录',
    // Sidebar
    'sidebar.current': '📋 当前名单',
    'sidebar.library': '🏫 班级库',
    'sidebar.studentList': '学生名单',
    'sidebar.noStudents': '暂无学生，请导入名单',
    'sidebar.addStudent': '添加学生...',
    'sidebar.import': '导入',
    'sidebar.clear': '清空',
    'sidebar.importTitle': '导入学生名单',
    'sidebar.importPaste': '粘贴姓名（每行一个）：',
    'sidebar.importConfirm': '确认导入',
    'sidebar.importFile': '或上传 TXT 文件：',
    'sidebar.expandPanel': '展开名单栏',
    'sidebar.collapsePanel': '折叠名单栏',
    'sidebar.persons': '人',
    // Header
    'header.login': '登录',
    'header.admin': '用户管理',
    'header.loading': '加载中...',
    // Settings
    'settings.title': '个性化设置',
    'settings.theme': '🎨 主题配色',
    'settings.font': '字体',
    'settings.fontSize': '字号',
    'settings.fontSmall': '小',
    'settings.fontLarge': '大',
    'settings.nickname': '昵称',
    'settings.nicknamePlaceholder': '设置昵称',
    'settings.save': '保存',
    'settings.saved': '已保存',
    'settings.logout': '退出登录',
    'settings.loggedOut': '已退出登录',
    'settings.profile': '个人资料',
    'settings.email': '邮箱',
    'settings.cloudSync': '☁️ 班级库数据已云端同步',
    'settings.localOnly': '🔒 数据仅保存于本地，安全无忧',
    // Random Picker
    'random.sound': '音效',
    'random.voice': '语音',
    'random.noRepeat': '不重复',
    'random.popup': '大字弹出',
    'random.seconds': '秒',
    'random.title': '随机选人',
    'random.wheelMode': '大转盘',
    'random.rollerMode': '滚轮模式',
    'random.persons': '人',
    'random.roll': '滚动',
    'random.pressToStop': '按任意键停止...',
    'random.selected': '选中',
    'random.picked': '已选',
    'random.remaining': '剩余',
    'random.reset': '重置',
    'random.clearList': '清空',
    'random.pickedList': '已选名单',
    'random.clickToClose': '点击空白处或按 ESC 关闭',
    'random.clickAnywhereClose': '点击任意处关闭',
    'random.spinning': '旋转中（点击转盘停止）',
    'random.spin': '旋转',
    'random.clickWheelStop': '点击转盘停止...',
    // Dice
    'dice.title': '🎲 智能骰子',
    'dice.subtitle': '(基于分组/建队)',
    'dice.mode': '骰子模式',
    'dice.basedOnGroup': '基于分组',
    'dice.basedOnTeam': '基于建队',
    'dice.throw': '🎲 投掷',
    'dice.groupTens': '组十位',
    'dice.groupOnes': '组个位',
    'dice.memberOnes': '成员个位',
    'dice.group': '组',
    'dice.member': '成员',
    'dice.groupResult': '第{0}组 第{1}人',
    'dice.groupDice': '(组数{0}→{1}个骰子定位组)',
    // Group Manager
    'group.title': '人员分组',
    'group.subtitle': '将 {0} 名学生随机分成若干组',
    'group.count': '组数',
    'group.autoGroup': '自动分组',
    'group.emptyTitle': '点击「自动分组」开始分配学生',
    'group.emptyDesc': '支持 2-10 组，可自定义组名、指定组长、拖拽调整',
    'group.namePrefix': '第{0}组',
    'group.exportName': '分组结果',
    // Team Builder
    'team.title': '建队',
    'team.subtitle': '按每队人数自动建队，可拖拽调整',
    'team.perTeam': '每队人数',
    'team.autoTeam': '自动建队',
    'team.emptyTitle': '点击「自动建队」开始组队',
    'team.emptyDesc': '设定每队人数后随机分配，支持拖拽调整',
    'team.namePrefix': '第{0}队',
    'team.exportName': '建队结果',
    // Toolkit
    'toolkit.title': '课堂工具箱',
    // Command Cards
    'cmd.title': '📢 课堂指令卡',
    'cmd.inputPlaceholder': '输入课堂指令主题，如：小组辩论',
    'cmd.searching': '检索中...',
    'cmd.searchBadge': '检索徽章',
    'cmd.noIcon': '图标候选不足，已使用默认"？"图标发布该指令',
    'cmd.searchFail': '联网检索图标失败，已使用默认"？"图标发布该指令',
    'cmd.foundIcons': '已找到 {0} 个候选图标，请点选一个用于"{1}"',
    'cmd.selectCandidate': '选择候选',
    'cmd.candidateIcon': '候选图标',
    'cmd.escOrClick': '按 ESC 或点击任意处退出',
    'cmd.quiet': '保持安静',
    'cmd.discuss': '分组讨论',
    'cmd.independent': '独立完成',
    'cmd.pairTalk': '同桌交流',
    'cmd.listen': '认真听讲',
    'cmd.raiseHand': '举手发言',
    // QR Code Generator
    'qr.title': '二维码生成器',
    'qr.placeholder': '输入网址...',
    'qr.scanTip': '📱 请用手机浏览器扫描访问',
    'qr.emptyTip': '输入网址即可实时生成二维码',
    // Noise Detector
    'noise.title': '🔊 噪音检测器',
    'noise.level': '音量',
    'noise.quiet': '安静',
    'noise.loud': '嘈杂',
    'noise.threshold': '警告阈值',
    'noise.peak': '峰值',
    'noise.tooLoud': '太吵了！请安静！',
    'noise.start': '开始检测',
    'noise.stop': '停止检测',
    // Random Assigner
    'assign.title': '🎯 随机分配器',
    'assign.inputPlaceholder': '输入任务名称...',
    'assign.info': '{0} 个任务，{1} 位学生',
    'assign.go': '随机分配',
    'assign.assigning': '分配中...',
    // Scoreboard
    'score.title': '🏆 课堂评分板',
    'score.addPlaceholder': '输入姓名或小组名...',
    'score.step': '步长',
    'score.empty': '添加学生或小组开始计分',
    'score.resetAll': '全部归零',
    // Lottery Drawer
    'lottery.title': '🎲 随机数/抽签',
    'lottery.modeNumber': '随机数',
    'lottery.modeLottery': '抽签',
    'lottery.min': '最小值',
    'lottery.max': '最大值',
    'lottery.roll': '生成随机数',
    'lottery.rolling': '生成中...',
    'lottery.draw': '开始抽签',
    'lottery.drawing': '抽签中...',
    'lottery.itemsPlaceholder': '每行一个选项...',
    'lottery.reset': '清除记录',
    'timer.title': '⏳ 倒计时器',
    'timer.start': '开始',
    'timer.pause': '暂停',
    'timer.reset': '重置',
    'timer.timeUp': '时间到！',
    'timer.enableReminder': '启用提醒',
    'timer.reminderTime': '提醒时间',
    'timer.secondsBefore': '秒前',
    'timer.voiceAnnounce': '语音播报',
    'timer.reminderSettings': '⏰ 提醒设置',
    'timer.reminderBefore': '秒前提醒',
    'timer.voiceOnly': '(语音)',
    'timer.colorOnly': '(仅变色)',
    'timer.secondsLeft': '⏰ 还剩 {0} 秒',
    'timer.exitFullscreen': '退出全屏 (ESC)',
    'timer.ttsReminder': '还剩{0}秒',
    // Barrage Discussion
    'barrage.title': '💬 讨论弹幕',
    'barrage.inputTopic': '输入讨论话题...',
    'barrage.publish': '🚀 发布话题并生成二维码',
    'barrage.privacy': '🔒 所有数据仅存本地数据库，不上传第三方',
    'barrage.messages': '条弹幕',
    'barrage.wall': '弹幕墙',
    'barrage.report': '智能报告',
    'barrage.wordcloud': '词云',
    'barrage.deleteTopic': '删除话题',
    'barrage.end': '结束',
    'barrage.play': '播放',
    'barrage.speed': '速度:',
    'barrage.waiting': '等待学生发送弹幕...',
    'barrage.analyzing': 'AI 正在分析弹幕内容...',
    'barrage.generatingCloud': 'AI 正在生成词云数据...',
    'barrage.reportTitle': '📊 智能分析报告',
    'barrage.noReport': '暂无报告',
    'barrage.noCloud': '暂无词云数据',
    'barrage.saveCloud': '保存词云',
    'barrage.scanToJoin': '学生扫码参与讨论',
    'barrage.topicCreated': '话题已创建',
    'barrage.topicCreatedDesc': '展示二维码让学生扫码参与',
    'barrage.topicUpdated': '话题已更新',
    'barrage.topicDeleted': '话题已删除',
    'barrage.createFailed': '创建失败',
    'barrage.editFailed': '修改失败',
    'barrage.deleteFailed': '删除失败',
    'barrage.deleteConfirm': '确定要删除该话题及所有弹幕数据吗？此操作不可撤销。',
    'barrage.editTitle': '修改话题标题',
    'barrage.newTitlePlaceholder': '输入新标题...',
    'barrage.cancel': '取消',
    'barrage.noData': '暂无弹幕数据',
    'barrage.analyzeFailed': '分析失败',
    'barrage.cloudParseFail': '词云解析失败',
    'barrage.analyzing2': '分析中...',
    'barrage.generating': '生成中...',
    // Check-in Panel
    'checkin.title': '课堂签到',
    'checkin.desc': '发起签到后，学生扫码即可完成签到',
    'checkin.duration': '签到时长',
    'checkin.minutes': '分钟',
    'checkin.start': '发起签到',
    'checkin.history': '查看签到历史',
    'checkin.historyTitle': '签到历史',
    'checkin.back': '返回',
    'checkin.noHistory': '暂无签到记录',
    'checkin.createFailed': '创建签到失败',
    'checkin.started': '签到已开始',
    'checkin.startedDesc': '时长 {0} 分钟',
    'checkin.ended': '签到已结束',
    'checkin.endCheckin': '结束签到',
    'checkin.checkedIn': '已签到',
    'checkin.unchecked': '未签到',
    'checkin.unknown': '未知',
    'checkin.leave': '请假',
    'checkin.absent': '缺勤',
    'checkin.scanToCheckin': '学生扫码签到',
    'checkin.stats': '签到统计',
    'checkin.rate': '签到率',
    'checkin.timeStats': '签到用时统计',
    'checkin.avgTime': '平均用时',
    'checkin.fastest': '最快',
    'checkin.slowest': '最慢',
    'checkin.unknownCheckin': '未知签到',
    'checkin.exportName': '签到记录',
    'checkin.csvName': '姓名',
    'checkin.csvStatus': '状态',
    'checkin.csvTime': '时间',
    'checkin.csvChecked': '已签到',
    'checkin.csvLeave': '请假',
    'checkin.csvUnchecked': '未签到',
    'checkin.csvUnknown': '未知',
    'checkin.secondsUnit': '秒',
    'checkin.minuteSecond': '{0}分{1}秒',
    // Seat Chart
    'seat.title': '座位安排',
    'seat.subtitle': '自定义教室布局，多种排座模式，支持拖拽交换座位和过道设置',
    'seat.rows': '行',
    'seat.cols': '列',
    'seat.groups': '组数',
    'seat.skipRow': '隔行',
    'seat.skipCol': '隔列',
    'seat.startFrom': '起始',
    'seat.fromDoor': '靠门开始',
    'seat.fromWindow': '靠窗开始',
    'seat.autoSeat': '自动排座',
    'seat.colAisle': '列过道',
    'seat.rowAisle': '行过道',
    'seat.checkin': '签到',
    'seat.exportName': '座位表',
    'seat.emptyTitle': '选择排座模式后点击「自动排座」',
    'seat.emptyDesc': '支持竖S形、横S形、按组排列、考试隔行等多种模式，可拖拽交换座位',
    'seat.podium': '🏫 讲 台',
    'seat.window': '窗户',
    'seat.door': '门',
    'seat.windowSide': '窗户侧',
    'seat.doorSide': '门侧',
    'seat.swapDoorWindow': '对换门窗位置',
    'seat.empty': '空',
    'seat.legend': '💡 拖拽学生交换座位 · 点击空座位可禁用/启用 · 拖动过道线可调整位置 · 双击过道线可删除',
    'seat.colLabel': '第{0}列',
    'seat.rowLabel': '第{0}行',
    'seat.enableRow': '点击开放本行座位',
    'seat.disableRow': '点击禁用本行座位',
    'seat.enableCol': '点击开放本列座位',
    'seat.disableCol': '点击禁用本列座位',
    'seat.colAisleAfter': '列过道 (第{0}列后)',
    'seat.rowAisleAfter': '行过道 (第{0}行后)',
    'seat.dragAisle': '按住并拖动调整过道位置，双击删除',
    'seat.dragAisleRow': '拖动调整过道位置，双击删除',
    // Seat modes
    'seatMode.verticalS': '竖S形',
    'seatMode.verticalSDesc': '按列蛇形排列',
    'seatMode.horizontalS': '横S形',
    'seatMode.horizontalSDesc': '按行蛇形排列',
    'seatMode.groupCol': '每组一列',
    'seatMode.groupColDesc': '同组学生在同一列',
    'seatMode.groupRow': '每组一排',
    'seatMode.groupRowDesc': '同组学生在同一行',
    'seatMode.smartCluster': '智能集中',
    'seatMode.smartClusterDesc': '各组紧凑相邻排列',
    'seatMode.random': '随机排座',
    'seatMode.randomDesc': '完全随机打乱',
    'seatMode.exam': '考试座位',
    'seatMode.examDesc': '按名单竖S形隔行入座',
    // Seat scenes
    'scene.classroom': '🏫 教室',
    'scene.classroomDesc': '传统教室网格布局',
    'scene.smartClassroom': '⭕ 智能教室',
    'scene.smartClassroomDesc': '圆形桌分组讨论',
    'scene.conference': '📋 会议室',
    'scene.conferenceDesc': '长条会议桌',
    'scene.concertHall': '🎵 音乐厅',
    'scene.concertHallDesc': '半圆形围绕舞台',
    'scene.banquet': '🎪 宴会厅',
    'scene.banquetDesc': '圆桌宴会布局',
    'scene.computerLab': '💻 机房',
    'scene.computerLabDesc': '长桌两侧对面坐',
    // Class Library
    'library.title': '班级库',
    'library.import': '导入',
    'library.export': '导出',
    'library.addCollege': '添加学院...',
    'library.addClass': '添加班级...',
    'library.noColleges': '暂无学院',
    'library.noCollegesHint': '添加学院或导入Excel',
    'library.selectClass': '选择一个班级查看学生名单',
    'library.loadToList': '加载到名单',
    'library.studentNumber': '学号',
    'library.studentName': '姓名',
    'library.noStudentsInClass': '该班级暂无学生',
    'library.loadedToList': '已加载到当前名单',
    'library.students': '名学生',
    'library.importPreview': '导入预览',
    'library.recordsParsed': '共解析',
    'library.records': '条记录',
    'library.college': '学院',
    'library.class': '班级',
    'library.existingClassHandling': '已有班级处理：',
    'library.append': '追加',
    'library.overwrite': '覆盖',
    'library.confirmImport': '确认导入',
    'library.cancel': '取消',
    'library.importSuccess': '导入成功',
    'library.addFailed': '添加失败',
    'library.fileEmpty': '文件为空或格式不正确',
    'library.parseFailed': '文件解析失败',
    'library.moreRecords': '...还有 {0} 条',
    // Export Buttons
    'export.namePlaceholder': '导出名称（回车缺省：{0}）',
    'export.exported': '已导出为 {0}',
    'export.failed': '导出失败',
    'export.retry': '请重试',
    // Auth Page
    'auth.appTitle': '互动课堂派',
    'auth.loginTitle': '登录账户',
    'auth.signupTitle': '创建账户',
    'auth.forgotTitle': '重置密码',
    'auth.emailPlaceholder': '邮箱地址',
    'auth.passwordPlaceholder': '密码',
    'auth.nicknamePlaceholder': '昵称（可选）',
    'auth.login': '登录',
    'auth.signup': '注册',
    'auth.loginFailed': '登录失败',
    'auth.signupFailed': '注册失败',
    'auth.signupSuccess': '注册成功',
    'auth.signupSuccessDesc': '请查收验证邮件后登录，管理员审批通过后可使用全部功能',
    'auth.signupNote': '注册后需管理员审批方可使用全部功能',
    'auth.noAccount': '没有账户？注册',
    'auth.hasAccount': '已有账户？登录',
    'auth.forgotPassword': '忘记密码',
    'auth.backToLogin': '返回登录',
    'auth.sendReset': '发送重置邮件',
    'auth.sending': '发送中...',
    'auth.sendFailed': '发送失败',
    'auth.resetSent': '重置邮件已发送',
    'auth.resetSentDesc': '请查收邮件',
    'auth.pleaseWait': '请稍候...',
    'auth.guestContinue': '以访客身份继续',
    'auth.pendingTitle': '等待审批',
    'auth.pendingDesc': '您的账户已注册成功，正在等待管理员审批。\n审批通过后即可使用全部功能。',
    'auth.pendingStatus': '审批中',
    'auth.guestBtn': '以访客继续',
    'auth.rejectedTitle': '审批未通过',
    'auth.rejectedDesc': '您的注册申请未通过审批。如有疑问请联系管理员。',
    // Reset Password
    'reset.title': '设置新密码',
    'reset.placeholder': '新密码（至少6位）',
    'reset.confirm': '确认重置',
    'reset.resetting': '重置中...',
    'reset.invalidLink': '无效的重置链接',
    'reset.backToLogin': '返回登录',
    'reset.minLength': '密码至少6位',
    'reset.failed': '重置失败',
    'reset.success': '密码已重置',
    // Admin Page
    'admin.title': '用户管理',
    'admin.back': '返回',
    'admin.searchPlaceholder': '搜索邮箱或昵称…',
    'admin.all': '全部',
    'admin.pending': '待审批',
    'admin.approved': '已批准',
    'admin.rejected': '已拒绝',
    'admin.selected': '已选 {0} 人',
    'admin.batchApprove': '批量批准',
    'admin.batchReject': '批量拒绝',
    'admin.approve': '批准',
    'admin.reject': '拒绝',
    'admin.changeToApprove': '改为批准',
    'admin.selectAll': '全选',
    'admin.noPending': '暂无待审批用户',
    'admin.operationFailed': '操作失败',
    'admin.noPermission': '无权限访问',
    'admin.adminOnly': '仅管理员可查看',
    'admin.sessionExpired': '登录状态失效',
    'admin.pleaseRelogin': '请重新登录后再试',
    'admin.batchResult': '已{0} {1} 位用户',
    // CheckIn Page (student-facing)
    'checkinPage.loading': '加载中...',
    'checkinPage.expired': '签到已结束',
    'checkinPage.expiredDesc': '此签到会话已过期或不存在',
    'checkinPage.success': '签到成功！',
    'checkinPage.completed': '{0} 已完成签到',
    'checkinPage.title': '课堂签到',
    'checkinPage.desc': '请输入您的姓名完成签到',
    'checkinPage.namePlaceholder': '请输入姓名',
    'checkinPage.checkinBtn': '签到',
    'checkinPage.checking': '签到中...',
    'checkinPage.failed': '签到失败，请重试',
    // Discuss Page
    'discuss.topicNotFound': '话题不存在或已过期',
    'discuss.loading': '加载中...',
    'discuss.enterNickname': '输入昵称即可参与讨论',
    'discuss.nicknamePlaceholder': '输入你的昵称...',
    'discuss.enterDiscussion': '进入讨论 🚀',
    'discuss.noRegister': '🔒 无需注册，昵称仅用于弹幕显示',
    'discuss.topic': '💬 讨论话题',
    'discuss.nickname': '昵称',
    'discuss.edit': '修改',
    'discuss.recentBarrage': '最近弹幕',
    'discuss.inputBarrage': '输入你的弹幕（最多50字）...',
    'discuss.sendFailed': '发送失败，请重试',
    'discuss.send': '发射 🚀',
    'discuss.sendingBtn': '发送中...',
    'discuss.sendSuccess': '✅ 发送成功！',
    'discuss.dataPrivacy': '🔒 所有数据仅用于课堂讨论',
    // Not Found
    'notFound.title': '页面未找到',
    'notFound.back': '返回首页',
    // Seat Checkin Page
    'seatCheckin.title': '座位签到',
    'seatCheckin.desc': '输入姓名查看你的座位位置',
    'seatCheckin.namePlaceholder': '请输入你的姓名',
    'seatCheckin.confirm': '确认签到',
    'seatCheckin.checking': '签到中...',
    'seatCheckin.loading': '加载中...',
    'seatCheckin.notFound': '签到会话不存在或已过期',
    'seatCheckin.success': '签到成功！',
    'seatCheckin.nameNotFound': '未找到该姓名',
    'seatCheckin.checkName': '请检查姓名是否正确',
    'seatCheckin.createFailed': '创建签到失败',
    'seatCheckin.sessionNotFound': '签到会话不存在',
    'seatCheckin.failed': '签到失败',
    // Seat Checkin Dialog
    'seatCheckinDialog.title': '座位签到',
    'seatCheckinDialog.desc': '生成签到二维码后，学生扫码输入姓名即可查看自己的座位位置，并获得导航指引。',
    'seatCheckinDialog.generate': '生成签到码',
    'seatCheckinDialog.generating': '生成中...',
    'seatCheckinDialog.checkedIn': '已签到',
    // Go Redirect
    'go.invalidLink': '无效链接',
    'go.redirecting': '正在跳转...',
    'go.openInBrowser': '在浏览器中打开',
    'go.wechatWarning': '当前为微信内置浏览器，请选择以下方式打开链接以获得最佳体验',
    'go.recommended': '推荐方式',
    'go.recommendedDesc': '点击右上角 ⋯ 菜单，选择「在默认浏览器中打开」',
    'go.copyLink': '复制链接',
    'go.copied': '已复制，请粘贴到浏览器打开',
    'go.tryDirect': '直接尝试打开',
    // WeChat Banner
    'wechat.warning': '当前为微信内置浏览器，部分功能可能受限。建议点击右上角「⋯」选择「在浏览器中打开」获得最佳体验。',
    // Common
    'common.save': '保存',
    'common.cancel': '取消',
    'common.confirm': '确认',
    'common.delete': '删除',
    'common.edit': '修改',
    'common.loading': '加载中...',
    'common.persons': '人',
    // Creative Board
    'board.title': '创意白板',
    'board.create': '创建白板',
    'board.myBoards': '我的白板',
    'board.noBoards': '还没有白板',
    'board.emptyHint': '创建一个白板，让学生通过卡片分享想法、协作讨论',
    'board.boardTitle': '白板标题',
    'board.boardDesc': '白板描述（可选）',
    'board.delete': '删除白板',
    'board.deleteConfirm': '确定要删除此白板吗？所有卡片将一并删除。',
    'board.settings': '白板设置',
    'board.lock': '锁定白板',
    'board.unlock': '解锁白板',
    'board.locked': '白板已锁定',
    'board.moderation': '审核模式',
    'board.moderationOn': '审核已开启',
    'board.moderationOff': '审核已关闭',
    'board.bannedWords': '违禁词（逗号分隔）',
    'board.viewWall': '墙模式',
    'board.viewKanban': '看板模式',
    'board.viewTimeline': '时间线',
    'board.viewCanvas': '自由画布',
    'board.addCard': '添加卡片',
    'board.cardContent': '输入内容...',
    'board.cardColor': '卡片颜色',
    'board.cardUrl': '链接 URL',
    'board.nickname': '你的昵称',
    'board.nicknamePlaceholder': '输入昵称...',
    'board.submit': '发布',
    'board.submitting': '发布中...',
    'board.submitSuccess': '发布成功！',
    'board.submitPage': '提交卡片',
    'board.joinBoard': '加入白板',
    'board.scanToJoin': '扫码加入白板',
    'board.pin': '置顶',
    'board.unpin': '取消置顶',
    'board.approve': '通过',
    'board.reject': '拒绝',
    'board.pending': '待审核',
    'board.pendingCount': '{0} 条待审核',
    'board.likes': '赞',
    'board.comments': '评论',
    'board.addComment': '添加评论...',
    'board.export': '导出',
    'board.exportCSV': '导出 CSV',
    'board.exportPNG': '导出截图',
    'board.pptMode': 'PPT 播放',
    'board.wordCloud': '词云',
    'board.wordCloudRefresh': '重新生成',
    'board.wordCloudEmpty': '卡片内容不足，无法生成词云',
    'board.wordCloudTheme': '配色主题',
    'board.smartReport': '智能报告',
    'board.reportGenerate': '生成报告',
    'board.reportGenerating': 'AI 分析中...',
    'board.reportRegenerate': '重新生成',
    'board.reportNoCards': '没有卡片内容，无法生成报告',
    'board.reportError': '报告生成失败，请稍后重试',
    'board.reportPrompt': '点击"生成报告"开始 AI 分析',
    'board.reportPromptSub': '将对 {0} 张卡片内容进行汇总分析',
    'board.reportCardCount': '张卡片',
    'board.reportStreaming': '正在生成中...',
    'ai.guestLimitReached': '今日 AI 使用次数已达上限，请登录后继续使用',
    'ai.guestRemaining': '访客每日可使用 AI {0}/{1} 次，登录后无限制',
    'board.pptPrev': '上一张',
    'board.pptNext': '下一张',
    'board.pptExit': '退出播放',
    'board.pptSlide': '{0} / {1}',
    'board.qrcode': '二维码',
    'board.shareLink': '分享链接',
    'board.anonymous': '匿名',
    'board.cardTypeText': '文本',
    'board.cardTypeImage': '图片',
    'board.cardTypeUrl': '链接',
    'board.columns': '看板列',
    'board.addColumn': '添加列',
    'board.blockedWord': '内容包含敏感词，已进入待审核',
    'board.lockedMsg': '白板已锁定，无法发布新内容',
    'board.back': '返回白板列表',
    'board.uploadImage': '上传图片',
    'board.uploadFile': '上传文件',
    'board.uploading': '上传中...',
    'board.downloadFile': '下载文件',
    'board.viewFile': '查看文件',
    'board.commentSend': '发送',
    'board.noComments': '暂无评论',
    'board.cloudSync': '☁️ 数据已同步到云端',
    // Quiz
    'quiz.title': '随堂测验',
    'quiz.questionBank': '题库',
    'quiz.addQuestion': '添加题目',
    'quiz.questionType': '题目类型',
    'quiz.single': '单选',
    'quiz.multi': '多选',
    'quiz.tf': '判断',
    'quiz.short': '简答',
    'quiz.questionContent': '题目内容',
    'quiz.questionPlaceholder': '请输入题目内容...',
    'quiz.options': '选项',
    'quiz.option': '选项',
    'quiz.addOption': '添加选项',
    'quiz.correctAnswer': '正确答案',
    'quiz.referenceAnswer': '参考答案（可选）',
    'quiz.tags': '标签',
    'quiz.tagsPlaceholder': '如：第一章、期中等',
    'quiz.save': '保存',
    'quiz.cancel': '取消',
    'quiz.saved': '题目已保存',
    'quiz.needOptions': '至少需要2个选项',
    'quiz.selectQuestions': '请选择题目',
    'quiz.defaultTitle': '随堂测验',
    'quiz.startSession': '发起测验',
    'quiz.endSession': '结束测验',
    'quiz.exportCSV': '导出结果',
    'quiz.sessionTitle': '测验标题',
    'quiz.active': '进行中',
    'quiz.ended': '已结束',
    'quiz.recentSessions': '测验记录',
    'quiz.noSessions': '暂无测验记录',
    'quiz.noQuestions': '题库为空',
    'quiz.noQuestionsHint': '添加题目到题库，选择后发起测验',
    'quiz.selectAll': '全选',
    'quiz.deselectAll': '取消全选',
    'quiz.selected': '已选',
    'quiz.questionsCount': '题',
    'quiz.scanToAnswer': '扫码答题',
    'quiz.submittedStudents': '已提交人数',
    'quiz.totalQuestions': '总题数',
    'quiz.accuracy': '正确率',
    'quiz.totalAnswers': '总答题数',
    'quiz.answers': '人作答',
    'quiz.studentList': '已答学生',
    'quiz.noData': '暂无数据',
    'quiz.true': '正确',
    'quiz.false': '错误',
    'quiz.enterName': '请输入你的姓名',
    'quiz.startAnswer': '开始答题',
    'quiz.prev': '上一题',
    'quiz.next': '下一题',
    'quiz.submit': '提交答案',
    'quiz.multiHint': '可选择多个选项',
    'quiz.shortPlaceholder': '请输入你的答案...',
    'quiz.submitSuccess': '提交成功！',
    'quiz.waitForResult': '请等待老师公布结果',
    'quiz.sessionNotFound': '测验不存在',
    'quiz.sessionEnded': '测验已结束',
    'quiz.loginRequired': '请登录后使用测验功能',
  },
  en: {
    'app.title': 'TeachMate',
    'app.subtitle': 'TeachMate |--Luoyang Institute of Technology--| limeng@lit.edu.cn',
    'tab.random': 'Random Pick',
    'tab.groups': 'Groups',
    'tab.teams': 'Teams',
    'tab.seats': 'Seats',
    'tab.checkin': 'Check-in',
    'tab.board': 'Board',
    'tab.toolkit': 'Toolkit',
    'tab.quiz': 'Quiz',
    'ext.ai': 'AI Assistant',
    'ext.idea': 'IdeaVas',
    'ext.tip': 'Log in with the same email as this platform',
    'sidebar.current': '📋 Current List',
    'sidebar.library': '🏫 Class Library',
    'sidebar.studentList': 'Student List',
    'sidebar.noStudents': 'No students yet. Please import a list.',
    'sidebar.addStudent': 'Add student...',
    'sidebar.import': 'Import',
    'sidebar.clear': 'Clear',
    'sidebar.importTitle': 'Import Student List',
    'sidebar.importPaste': 'Paste names (one per line):',
    'sidebar.importConfirm': 'Confirm Import',
    'sidebar.importFile': 'Or upload a TXT file:',
    'sidebar.expandPanel': 'Expand list panel',
    'sidebar.collapsePanel': 'Collapse list panel',
    'sidebar.persons': '',
    'header.login': 'Login',
    'header.admin': 'User Management',
    'header.loading': 'Loading...',
    'settings.title': 'Settings',
    'settings.theme': '🎨 Color Theme',
    'settings.font': 'Font',
    'settings.fontSize': 'Font Size',
    'settings.fontSmall': 'S',
    'settings.fontLarge': 'L',
    'settings.nickname': 'Nickname',
    'settings.nicknamePlaceholder': 'Set nickname',
    'settings.save': 'Save',
    'settings.saved': 'Saved',
    'settings.logout': 'Sign Out',
    'settings.loggedOut': 'Signed out',
    'settings.profile': 'Profile',
    'settings.email': 'Email',
    'settings.cloudSync': '☁️ Class data synced to cloud',
    'settings.localOnly': '🔒 Data stored locally only',
    'random.sound': 'Sound',
    'random.voice': 'Voice',
    'random.noRepeat': 'No Repeat',
    'random.popup': 'Pop-up',
    'random.seconds': 's',
    'random.title': 'Random Pick',
    'random.wheelMode': 'Spin Wheel',
    'random.rollerMode': 'Roller Mode',
    'random.persons': '',
    'random.roll': 'Roll',
    'random.pressToStop': 'Press any key to stop...',
    'random.selected': 'Selected',
    'random.picked': 'Picked',
    'random.remaining': 'Remaining',
    'random.reset': 'Reset',
    'random.clearList': 'Clear',
    'random.pickedList': 'Picked List',
    'random.clickToClose': 'Click blank area or press ESC to close',
    'random.clickAnywhereClose': 'Click anywhere to close',
    'random.spinning': 'Spinning (click wheel to stop)',
    'random.spin': 'Spin',
    'random.clickWheelStop': 'Click wheel to stop...',
    'dice.title': '🎲 Smart Dice',
    'dice.subtitle': '(based on groups/teams)',
    'dice.mode': 'Dice Mode',
    'dice.basedOnGroup': 'By Group',
    'dice.basedOnTeam': 'By Team',
    'dice.throw': '🎲 Roll',
    'dice.groupTens': 'Group tens',
    'dice.groupOnes': 'Group ones',
    'dice.memberOnes': 'Member ones',
    'dice.group': 'Group',
    'dice.member': 'Member',
    'dice.groupResult': 'Group {0} Member {1}',
    'dice.groupDice': '(Groups {0} → {1} dice)',
    'group.title': 'Grouping',
    'group.subtitle': 'Randomly split {0} students into groups',
    'group.count': 'Groups',
    'group.autoGroup': 'Auto Group',
    'group.emptyTitle': 'Click "Auto Group" to assign students',
    'group.emptyDesc': 'Supports 2-10 groups, custom names, leaders, drag to adjust',
    'group.namePrefix': 'Group {0}',
    'group.exportName': 'Group Results',
    'team.title': 'Teams',
    'team.subtitle': 'Auto-create teams by size, drag to adjust',
    'team.perTeam': 'Per team',
    'team.autoTeam': 'Auto Team',
    'team.emptyTitle': 'Click "Auto Team" to start',
    'team.emptyDesc': 'Set team size then randomly assign, drag to adjust',
    'team.namePrefix': 'Team {0}',
    'team.exportName': 'Team Results',
    'toolkit.title': 'Classroom Toolkit',
    'cmd.title': '📢 Command Cards',
    'cmd.inputPlaceholder': 'Enter command topic, e.g.: Group debate',
    'cmd.searching': 'Searching...',
    'cmd.searchBadge': 'Search Badge',
    'cmd.noIcon': 'Not enough icon candidates, used default "?" icon',
    'cmd.searchFail': 'Icon search failed, used default "?" icon',
    'cmd.foundIcons': 'Found {0} candidate icons for "{1}"',
    'cmd.selectCandidate': 'Select candidate',
    'cmd.candidateIcon': 'Candidate icon',
    'cmd.escOrClick': 'Press ESC or click anywhere to exit',
    'cmd.quiet': 'Be Quiet',
    'cmd.discuss': 'Group Discussion',
    'cmd.independent': 'Work Independently',
    'cmd.pairTalk': 'Pair Talk',
    'cmd.listen': 'Listen Carefully',
    'cmd.raiseHand': 'Raise Hand',
    'qr.title': 'QR Code Generator',
    'qr.placeholder': 'Enter URL...',
    'qr.scanTip': '📱 Scan with mobile browser',
    'qr.emptyTip': 'Enter a URL to generate QR code',
    'noise.title': '🔊 Noise Detector',
    'noise.level': 'Volume',
    'noise.quiet': 'Quiet',
    'noise.loud': 'Loud',
    'noise.threshold': 'Warning threshold',
    'noise.peak': 'Peak',
    'noise.tooLoud': 'Too loud! Please be quiet!',
    'noise.start': 'Start monitoring',
    'noise.stop': 'Stop monitoring',
    'assign.title': '🎯 Random Assigner',
    'assign.inputPlaceholder': 'Enter task name...',
    'assign.info': '{0} tasks, {1} students',
    'assign.go': 'Assign randomly',
    'assign.assigning': 'Assigning...',
    'score.title': '🏆 Scoreboard',
    'score.addPlaceholder': 'Enter name or team...',
    'score.step': 'Step',
    'score.empty': 'Add students or teams to start scoring',
    'score.resetAll': 'Reset all',
    'lottery.title': '🎲 Random / Lottery',
    'lottery.modeNumber': 'Number',
    'lottery.modeLottery': 'Lottery',
    'lottery.min': 'Min',
    'lottery.max': 'Max',
    'lottery.roll': 'Generate',
    'lottery.rolling': 'Rolling...',
    'lottery.draw': 'Draw',
    'lottery.drawing': 'Drawing...',
    'lottery.itemsPlaceholder': 'One item per line...',
    'lottery.reset': 'Clear history',
    'timer.title': '⏳ Countdown Timer',
    'timer.start': 'Start',
    'timer.pause': 'Pause',
    'timer.reset': 'Reset',
    'timer.timeUp': "Time's up!",
    'timer.enableReminder': 'Enable Reminder',
    'timer.reminderTime': 'Reminder Time',
    'timer.secondsBefore': 's before',
    'timer.voiceAnnounce': 'Voice',
    'timer.reminderSettings': '⏰ Reminder Settings',
    'timer.reminderBefore': 's reminder',
    'timer.voiceOnly': '(voice)',
    'timer.colorOnly': '(color only)',
    'timer.secondsLeft': '⏰ {0} seconds left',
    'timer.exitFullscreen': 'Exit fullscreen (ESC)',
    'timer.ttsReminder': '{0} seconds remaining',
    'barrage.title': '💬 Barrage Discussion',
    'barrage.inputTopic': 'Enter discussion topic...',
    'barrage.publish': '🚀 Publish & Generate QR',
    'barrage.privacy': '🔒 All data stored locally only',
    'barrage.messages': 'messages',
    'barrage.wall': 'Barrage Wall',
    'barrage.report': 'AI Report',
    'barrage.wordcloud': 'Word Cloud',
    'barrage.deleteTopic': 'Delete Topic',
    'barrage.end': 'End',
    'barrage.play': 'Play',
    'barrage.speed': 'Speed:',
    'barrage.waiting': 'Waiting for student messages...',
    'barrage.analyzing': 'AI is analyzing messages...',
    'barrage.generatingCloud': 'AI is generating word cloud...',
    'barrage.reportTitle': '📊 AI Analysis Report',
    'barrage.noReport': 'No report yet',
    'barrage.noCloud': 'No word cloud data',
    'barrage.saveCloud': 'Save Word Cloud',
    'barrage.scanToJoin': 'Students scan to join discussion',
    'barrage.topicCreated': 'Topic created',
    'barrage.topicCreatedDesc': 'Show QR code for students to join',
    'barrage.topicUpdated': 'Topic updated',
    'barrage.topicDeleted': 'Topic deleted',
    'barrage.createFailed': 'Creation failed',
    'barrage.editFailed': 'Edit failed',
    'barrage.deleteFailed': 'Delete failed',
    'barrage.deleteConfirm': 'Delete this topic and all barrage data? This cannot be undone.',
    'barrage.editTitle': 'Edit Topic Title',
    'barrage.newTitlePlaceholder': 'Enter new title...',
    'barrage.cancel': 'Cancel',
    'barrage.noData': 'No barrage data',
    'barrage.analyzeFailed': 'Analysis failed',
    'barrage.cloudParseFail': 'Word cloud parse failed',
    'barrage.analyzing2': 'Analyzing...',
    'barrage.generating': 'Generating...',
    'checkin.title': 'Check-in',
    'checkin.desc': 'Students scan QR code to check in',
    'checkin.duration': 'Duration',
    'checkin.minutes': 'min',
    'checkin.start': 'Start Check-in',
    'checkin.history': 'View History',
    'checkin.historyTitle': 'Check-in History',
    'checkin.back': 'Back',
    'checkin.noHistory': 'No check-in records',
    'checkin.createFailed': 'Failed to create check-in',
    'checkin.started': 'Check-in started',
    'checkin.startedDesc': 'Duration: {0} minutes',
    'checkin.ended': 'Check-in ended',
    'checkin.endCheckin': 'End Check-in',
    'checkin.checkedIn': 'Checked in',
    'checkin.unchecked': 'Not checked in',
    'checkin.unknown': 'Unknown',
    'checkin.leave': 'Leave',
    'checkin.absent': 'Absent',
    'checkin.scanToCheckin': 'Scan to check in',
    'checkin.stats': 'Check-in Statistics',
    'checkin.rate': 'Rate',
    'checkin.timeStats': 'Time Statistics',
    'checkin.avgTime': 'Average',
    'checkin.fastest': 'Fastest',
    'checkin.slowest': 'Slowest',
    'checkin.unknownCheckin': 'Unknown check-ins',
    'checkin.exportName': 'Check-in Record',
    'checkin.csvName': 'Name',
    'checkin.csvStatus': 'Status',
    'checkin.csvTime': 'Time',
    'checkin.csvChecked': 'Checked in',
    'checkin.csvLeave': 'Leave',
    'checkin.csvUnchecked': 'Not checked in',
    'checkin.csvUnknown': 'Unknown',
    'checkin.secondsUnit': 's',
    'checkin.minuteSecond': '{0}m{1}s',
    'seat.title': 'Seating Chart',
    'seat.subtitle': 'Custom layout, multiple modes, drag to swap, aisle settings',
    'seat.rows': 'Rows',
    'seat.cols': 'Cols',
    'seat.groups': 'Groups',
    'seat.skipRow': 'Skip Row',
    'seat.skipCol': 'Skip Col',
    'seat.startFrom': 'Start',
    'seat.fromDoor': 'From door',
    'seat.fromWindow': 'From window',
    'seat.autoSeat': 'Auto Seat',
    'seat.colAisle': 'Col Aisle',
    'seat.rowAisle': 'Row Aisle',
    'seat.checkin': 'Check-in',
    'seat.exportName': 'Seating Chart',
    'seat.emptyTitle': 'Select a mode then click "Auto Seat"',
    'seat.emptyDesc': 'Multiple modes: S-shape, group, exam spacing. Drag to swap seats.',
    'seat.podium': '🏫 Podium',
    'seat.window': 'Window',
    'seat.door': 'Door',
    'seat.windowSide': 'Window Side',
    'seat.doorSide': 'Door Side',
    'seat.swapDoorWindow': 'Swap door/window sides',
    'seat.empty': '—',
    'seat.legend': '💡 Drag to swap · Click empty seat to disable · Drag aisle to reposition · Double-click aisle to remove',
    'seat.colLabel': 'Col {0}',
    'seat.rowLabel': 'Row {0}',
    'seat.enableRow': 'Click to enable this row',
    'seat.disableRow': 'Click to disable this row',
    'seat.enableCol': 'Click to enable this column',
    'seat.disableCol': 'Click to disable this column',
    'seat.colAisleAfter': 'Col aisle (after col {0})',
    'seat.rowAisleAfter': 'Row aisle (after row {0})',
    'seat.dragAisle': 'Drag to move, double-click to remove',
    'seat.dragAisleRow': 'Drag to move, double-click to remove',
    'seatMode.verticalS': 'Vertical S',
    'seatMode.verticalSDesc': 'Snake by column',
    'seatMode.horizontalS': 'Horizontal S',
    'seatMode.horizontalSDesc': 'Snake by row',
    'seatMode.groupCol': 'Group/Col',
    'seatMode.groupColDesc': 'Same group in same column',
    'seatMode.groupRow': 'Group/Row',
    'seatMode.groupRowDesc': 'Same group in same row',
    'seatMode.smartCluster': 'Smart Cluster',
    'seatMode.smartClusterDesc': 'Groups clustered together',
    'seatMode.random': 'Random',
    'seatMode.randomDesc': 'Fully random shuffle',
    'seatMode.exam': 'Exam',
    'seatMode.examDesc': 'S-shape with row/col gaps',
    'scene.classroom': '🏫 Classroom',
    'scene.classroomDesc': 'Traditional grid layout',
    'scene.smartClassroom': '⭕ Smart Classroom',
    'scene.smartClassroomDesc': 'Round table groups',
    'scene.conference': '📋 Conference',
    'scene.conferenceDesc': 'Conference table',
    'scene.concertHall': '🎵 Concert Hall',
    'scene.concertHallDesc': 'Semicircle around stage',
    'scene.banquet': '🎪 Banquet Hall',
    'scene.banquetDesc': 'Round table banquet',
    'scene.computerLab': '💻 Computer Lab',
    'scene.computerLabDesc': 'Long tables face-to-face',
    'library.title': 'Class Library',
    'library.import': 'Import',
    'library.export': 'Export',
    'library.addCollege': 'Add college...',
    'library.addClass': 'Add class...',
    'library.noColleges': 'No colleges yet',
    'library.noCollegesHint': 'Add a college or import Excel',
    'library.selectClass': 'Select a class to view students',
    'library.loadToList': 'Load to List',
    'library.studentNumber': 'ID',
    'library.studentName': 'Name',
    'library.noStudentsInClass': 'No students in this class',
    'library.loadedToList': 'Loaded to current list',
    'library.students': 'students',
    'library.importPreview': 'Import Preview',
    'library.recordsParsed': 'Parsed',
    'library.records': 'records',
    'library.college': 'College',
    'library.class': 'Class',
    'library.existingClassHandling': 'Existing class:',
    'library.append': 'Append',
    'library.overwrite': 'Overwrite',
    'library.confirmImport': 'Confirm Import',
    'library.cancel': 'Cancel',
    'library.importSuccess': 'Import successful',
    'library.addFailed': 'Add failed',
    'library.fileEmpty': 'File is empty or invalid format',
    'library.parseFailed': 'File parse failed',
    'library.moreRecords': '...{0} more',
    'export.namePlaceholder': 'Export name (default: {0})',
    'export.exported': 'Exported as {0}',
    'export.failed': 'Export failed',
    'export.retry': 'Please retry',
    'auth.appTitle': 'TeachMate',
    'auth.loginTitle': 'Sign In',
    'auth.signupTitle': 'Create Account',
    'auth.forgotTitle': 'Reset Password',
    'auth.emailPlaceholder': 'Email',
    'auth.passwordPlaceholder': 'Password',
    'auth.nicknamePlaceholder': 'Nickname (optional)',
    'auth.login': 'Sign In',
    'auth.signup': 'Sign Up',
    'auth.loginFailed': 'Login failed',
    'auth.signupFailed': 'Signup failed',
    'auth.signupSuccess': 'Signup successful',
    'auth.signupSuccessDesc': 'Please verify your email. Admin approval required for full access.',
    'auth.signupNote': 'Admin approval required for full access',
    'auth.noAccount': "No account? Sign up",
    'auth.hasAccount': 'Have an account? Sign in',
    'auth.forgotPassword': 'Forgot password',
    'auth.backToLogin': 'Back to login',
    'auth.sendReset': 'Send Reset Email',
    'auth.sending': 'Sending...',
    'auth.sendFailed': 'Send failed',
    'auth.resetSent': 'Reset email sent',
    'auth.resetSentDesc': 'Please check your email',
    'auth.pleaseWait': 'Please wait...',
    'auth.guestContinue': 'Continue as guest',
    'auth.pendingTitle': 'Pending Approval',
    'auth.pendingDesc': 'Your account is registered. Waiting for admin approval.\nFull features available after approval.',
    'auth.pendingStatus': 'Pending',
    'auth.guestBtn': 'Continue as guest',
    'auth.rejectedTitle': 'Not Approved',
    'auth.rejectedDesc': 'Your application was not approved. Contact admin for details.',
    'reset.title': 'Set New Password',
    'reset.placeholder': 'New password (min 6 chars)',
    'reset.confirm': 'Confirm Reset',
    'reset.resetting': 'Resetting...',
    'reset.invalidLink': 'Invalid reset link',
    'reset.backToLogin': 'Back to login',
    'reset.minLength': 'Password must be at least 6 characters',
    'reset.failed': 'Reset failed',
    'reset.success': 'Password reset successful',
    'admin.title': 'User Management',
    'admin.back': 'Back',
    'admin.searchPlaceholder': 'Search email or nickname...',
    'admin.all': 'All',
    'admin.pending': 'Pending',
    'admin.approved': 'Approved',
    'admin.rejected': 'Rejected',
    'admin.selected': '{0} selected',
    'admin.batchApprove': 'Batch Approve',
    'admin.batchReject': 'Batch Reject',
    'admin.approve': 'Approve',
    'admin.reject': 'Reject',
    'admin.changeToApprove': 'Approve',
    'admin.selectAll': 'Select All',
    'admin.noPending': 'No pending users',
    'admin.operationFailed': 'Operation failed',
    'admin.noPermission': 'Access denied',
    'admin.adminOnly': 'Admin only',
    'admin.sessionExpired': 'Session expired',
    'admin.pleaseRelogin': 'Please login again',
    'admin.batchResult': '{0} {1} users',
    'checkinPage.loading': 'Loading...',
    'checkinPage.expired': 'Check-in Ended',
    'checkinPage.expiredDesc': 'This check-in session has expired or does not exist',
    'checkinPage.success': 'Check-in Successful!',
    'checkinPage.completed': '{0} has checked in',
    'checkinPage.title': 'Check-in',
    'checkinPage.desc': 'Enter your name to check in',
    'checkinPage.namePlaceholder': 'Enter your name',
    'checkinPage.checkinBtn': 'Check In',
    'checkinPage.checking': 'Checking in...',
    'checkinPage.failed': 'Check-in failed, please retry',
    'discuss.topicNotFound': 'Topic not found or expired',
    'discuss.loading': 'Loading...',
    'discuss.enterNickname': 'Enter a nickname to join',
    'discuss.nicknamePlaceholder': 'Enter your nickname...',
    'discuss.enterDiscussion': 'Join Discussion 🚀',
    'discuss.noRegister': '🔒 No registration needed',
    'discuss.topic': '💬 Discussion Topic',
    'discuss.nickname': 'Nickname',
    'discuss.edit': 'Edit',
    'discuss.recentBarrage': 'Recent Messages',
    'discuss.inputBarrage': 'Enter your message (max 50 chars)...',
    'discuss.sendFailed': 'Send failed, please retry',
    'discuss.send': 'Send 🚀',
    'discuss.sendingBtn': 'Sending...',
    'discuss.sendSuccess': '✅ Sent successfully!',
    'discuss.dataPrivacy': '🔒 All data used for classroom discussion only',
    'notFound.title': 'Page not found',
    'notFound.back': 'Return to Home',
    'seatCheckin.title': 'Seat Check-in',
    'seatCheckin.desc': 'Enter your name to find your seat',
    'seatCheckin.namePlaceholder': 'Enter your name',
    'seatCheckin.confirm': 'Confirm Check-in',
    'seatCheckin.checking': 'Checking in...',
    'seatCheckin.loading': 'Loading...',
    'seatCheckin.notFound': 'Session not found or expired',
    'seatCheckin.success': 'Check-in Successful!',
    'seatCheckin.nameNotFound': 'Name not found',
    'seatCheckin.checkName': 'Please check your name',
    'seatCheckin.createFailed': 'Failed to create check-in',
    'seatCheckin.sessionNotFound': 'Session not found',
    'seatCheckin.failed': 'Check-in failed',
    'seatCheckinDialog.title': 'Seat Check-in',
    'seatCheckinDialog.desc': 'Generate QR code for students to find their seats.',
    'seatCheckinDialog.generate': 'Generate QR Code',
    'seatCheckinDialog.generating': 'Generating...',
    'seatCheckinDialog.checkedIn': 'Checked in',
    'go.invalidLink': 'Invalid link',
    'go.redirecting': 'Redirecting...',
    'go.openInBrowser': 'Open in Browser',
    'go.wechatWarning': 'You are using WeChat browser. Please use one of the methods below for the best experience.',
    'go.recommended': 'Recommended',
    'go.recommendedDesc': 'Tap the ⋯ menu in the top right, then select "Open in Browser"',
    'go.copyLink': 'Copy Link',
    'go.copied': 'Copied! Paste in your browser',
    'go.tryDirect': 'Try opening directly',
    'wechat.warning': 'You are using WeChat browser. Some features may be limited. Tap ⋯ → "Open in Browser" for the best experience.',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.loading': 'Loading...',
    'common.persons': '',
    'board.title': 'Creative Board',
    'board.create': 'Create Board',
    'board.myBoards': 'My Boards',
    'board.noBoards': 'No boards yet',
    'board.emptyHint': 'Create a board to let students share ideas and collaborate with cards',
    'board.boardTitle': 'Board Title',
    'board.boardDesc': 'Description (optional)',
    'board.delete': 'Delete Board',
    'board.deleteConfirm': 'Delete this board? All cards will be removed.',
    'board.settings': 'Board Settings',
    'board.lock': 'Lock Board',
    'board.unlock': 'Unlock Board',
    'board.locked': 'Board Locked',
    'board.moderation': 'Moderation',
    'board.moderationOn': 'Moderation enabled',
    'board.moderationOff': 'Moderation disabled',
    'board.bannedWords': 'Banned words (comma-separated)',
    'board.viewWall': 'Wall',
    'board.viewKanban': 'Kanban',
    'board.viewTimeline': 'Timeline',
    'board.viewCanvas': 'Canvas',
    'board.addCard': 'Add Card',
    'board.cardContent': 'Enter content...',
    'board.cardColor': 'Card Color',
    'board.cardUrl': 'URL',
    'board.nickname': 'Your Nickname',
    'board.nicknamePlaceholder': 'Enter nickname...',
    'board.submit': 'Post',
    'board.submitting': 'Posting...',
    'board.submitSuccess': 'Posted successfully!',
    'board.submitPage': 'Submit Card',
    'board.joinBoard': 'Join Board',
    'board.scanToJoin': 'Scan to join board',
    'board.pin': 'Pin',
    'board.unpin': 'Unpin',
    'board.approve': 'Approve',
    'board.reject': 'Reject',
    'board.pending': 'Pending',
    'board.pendingCount': '{0} pending',
    'board.likes': 'Like',
    'board.comments': 'Comments',
    'board.addComment': 'Add comment...',
    'board.export': 'Export',
    'board.exportCSV': 'Export CSV',
    'board.exportPNG': 'Export Screenshot',
    'board.pptMode': 'Slideshow',
    'board.wordCloud': 'Word Cloud',
    'board.wordCloudRefresh': 'Regenerate',
    'board.wordCloudEmpty': 'Not enough card content to generate word cloud',
    'board.wordCloudTheme': 'Theme',
    'board.smartReport': 'Smart Report',
    'board.reportGenerate': 'Generate Report',
    'board.reportGenerating': 'AI analyzing...',
    'board.reportRegenerate': 'Regenerate',
    'board.reportNoCards': 'No cards to analyze',
    'board.reportError': 'Report generation failed, please retry',
    'board.reportPrompt': 'Click "Generate Report" to start AI analysis',
    'board.reportPromptSub': 'Analyze content from {0} cards',
    'board.reportCardCount': 'cards',
    'board.reportStreaming': 'Generating...',
    'ai.guestLimitReached': 'Daily AI limit reached. Please log in for unlimited access',
    'ai.guestRemaining': 'Guest AI usage: {0}/{1} remaining today. Log in for unlimited',
    'board.pptPrev': 'Previous',
    'board.pptNext': 'Next',
    'board.pptExit': 'Exit Slideshow',
    'board.pptSlide': '{0} / {1}',
    'board.qrcode': 'QR Code',
    'board.shareLink': 'Share Link',
    'board.anonymous': 'Anonymous',
    'board.cardTypeText': 'Text',
    'board.cardTypeImage': 'Image',
    'board.cardTypeUrl': 'Link',
    'board.columns': 'Columns',
    'board.addColumn': 'Add Column',
    'board.blockedWord': 'Content flagged for review',
    'board.lockedMsg': 'Board is locked. No new posts allowed.',
    'board.back': 'Back to boards',
    'board.uploadImage': 'Upload Image',
    'board.uploadFile': 'Upload File',
    'board.uploading': 'Uploading...',
    'board.downloadFile': 'Download',
    'board.viewFile': 'View File',
    'board.commentSend': 'Send',
    'board.noComments': 'No comments yet',
    'board.cloudSync': '☁️ Synced to cloud',
    // Quiz
    'quiz.title': 'Quiz',
    'quiz.questionBank': 'Question Bank',
    'quiz.addQuestion': 'Add Question',
    'quiz.questionType': 'Question Type',
    'quiz.single': 'Single Choice',
    'quiz.multi': 'Multiple Choice',
    'quiz.tf': 'True/False',
    'quiz.short': 'Short Answer',
    'quiz.questionContent': 'Question',
    'quiz.questionPlaceholder': 'Enter question...',
    'quiz.options': 'Options',
    'quiz.option': 'Option',
    'quiz.addOption': 'Add Option',
    'quiz.correctAnswer': 'Correct Answer',
    'quiz.referenceAnswer': 'Reference answer (optional)',
    'quiz.tags': 'Tags',
    'quiz.tagsPlaceholder': 'e.g. Chapter 1, Midterm',
    'quiz.save': 'Save',
    'quiz.cancel': 'Cancel',
    'quiz.saved': 'Question saved',
    'quiz.needOptions': 'At least 2 options required',
    'quiz.selectQuestions': 'Please select questions',
    'quiz.defaultTitle': 'Quick Quiz',
    'quiz.startSession': 'Start Quiz',
    'quiz.endSession': 'End Quiz',
    'quiz.exportCSV': 'Export Results',
    'quiz.sessionTitle': 'Quiz Title',
    'quiz.active': 'Active',
    'quiz.ended': 'Ended',
    'quiz.recentSessions': 'Recent Sessions',
    'quiz.noSessions': 'No sessions yet',
    'quiz.noQuestions': 'No questions yet',
    'quiz.noQuestionsHint': 'Add questions to the bank, then start a quiz',
    'quiz.selectAll': 'Select All',
    'quiz.deselectAll': 'Deselect All',
    'quiz.selected': 'Selected',
    'quiz.questionsCount': 'Q',
    'quiz.scanToAnswer': 'Scan to Answer',
    'quiz.submittedStudents': 'Submitted',
    'quiz.totalQuestions': 'Total Questions',
    'quiz.accuracy': 'Accuracy',
    'quiz.totalAnswers': 'Total Answers',
    'quiz.answers': 'answered',
    'quiz.studentList': 'Students',
    'quiz.noData': 'No data',
    'quiz.true': 'True',
    'quiz.false': 'False',
    'quiz.enterName': 'Enter your name',
    'quiz.startAnswer': 'Start',
    'quiz.prev': 'Previous',
    'quiz.next': 'Next',
    'quiz.submit': 'Submit',
    'quiz.multiHint': 'Select multiple options',
    'quiz.shortPlaceholder': 'Enter your answer...',
    'quiz.submitSuccess': 'Submitted!',
    'quiz.waitForResult': 'Please wait for the teacher to announce results',
    'quiz.sessionNotFound': 'Quiz not found',
    'quiz.sessionEnded': 'Quiz has ended',
    'quiz.loginRequired': 'Please log in to use quiz features',
  },
  ru: {
    'app.title': 'TeachMate',
    'app.subtitle': 'TeachMate |--Лоянский технологический институт--| limeng@lit.edu.cn',
    'tab.random': 'Случайный выбор',
    'tab.groups': 'Группы',
    'tab.teams': 'Команды',
    'tab.seats': 'Места',
    'tab.checkin': 'Отметка',
    'tab.board': 'Доска',
    'tab.toolkit': 'Инструменты',
    'ext.ai': 'ИИ Помощник',
    'ext.idea': 'IdeaVas',
    'ext.tip': 'Войдите с тем же email',
    'sidebar.current': '📋 Текущий список',
    'sidebar.library': '🏫 Библиотека классов',
    'sidebar.studentList': 'Список студентов',
    'sidebar.noStudents': 'Нет студентов. Импортируйте список.',
    'sidebar.addStudent': 'Добавить...',
    'sidebar.import': 'Импорт',
    'sidebar.clear': 'Очистить',
    'sidebar.importTitle': 'Импорт списка',
    'sidebar.importPaste': 'Вставьте имена (по одному в строке):',
    'sidebar.importConfirm': 'Подтвердить',
    'sidebar.importFile': 'Или загрузите TXT файл:',
    'sidebar.expandPanel': 'Развернуть',
    'sidebar.collapsePanel': 'Свернуть',
    'sidebar.persons': '',
    'header.login': 'Войти',
    'header.admin': 'Управление',
    'header.loading': 'Загрузка...',
    'settings.title': 'Настройки',
    'settings.theme': '🎨 Тема',
    'settings.font': 'Шрифт',
    'settings.fontSize': 'Размер',
    'settings.fontSmall': 'М',
    'settings.fontLarge': 'Б',
    'settings.nickname': 'Псевдоним',
    'settings.nicknamePlaceholder': 'Задать псевдоним',
    'settings.save': 'Сохранить',
    'settings.saved': 'Сохранено',
    'settings.logout': 'Выйти',
    'settings.loggedOut': 'Вы вышли',
    'settings.profile': 'Профиль',
    'settings.email': 'Email',
    'settings.cloudSync': '☁️ Данные синхронизированы',
    'settings.localOnly': '🔒 Данные хранятся локально',
    'random.sound': 'Звук',
    'random.voice': 'Голос',
    'random.noRepeat': 'Без повтора',
    'random.popup': 'Всплывающее',
    'random.seconds': 'с',
    'random.title': 'Случайный выбор',
    'random.wheelMode': 'Колесо',
    'random.rollerMode': 'Барабан',
    'random.persons': '',
    'random.roll': 'Крутить',
    'random.pressToStop': 'Нажмите любую клавишу...',
    'random.selected': 'Выбран',
    'random.picked': 'Выбрано',
    'random.remaining': 'Осталось',
    'random.reset': 'Сброс',
    'random.clearList': 'Очистить',
    'random.pickedList': 'Список выбранных',
    'random.clickToClose': 'Нажмите ESC или вне области для закрытия',
    'random.clickAnywhereClose': 'Нажмите для закрытия',
    'random.spinning': 'Вращается (нажмите для остановки)',
    'random.spin': 'Крутить',
    'random.clickWheelStop': 'Нажмите для остановки...',
    'dice.title': '🎲 Умные кости',
    'dice.subtitle': '(по группам/командам)',
    'dice.mode': 'Режим',
    'dice.basedOnGroup': 'По группе',
    'dice.basedOnTeam': 'По команде',
    'dice.throw': '🎲 Бросить',
    'dice.group': 'Группа',
    'dice.member': 'Участник',
    'dice.groupResult': 'Группа {0} Участник {1}',
    'dice.groupDice': '(Групп {0} → {1} кости)',
    'group.title': 'Группировка',
    'group.subtitle': 'Разделить {0} студентов на группы',
    'group.count': 'Кол-во',
    'group.autoGroup': 'Авто группы',
    'group.emptyTitle': 'Нажмите «Авто группы»',
    'group.emptyDesc': '2-10 групп, настраиваемые имена, лидеры, перетаскивание',
    'group.namePrefix': 'Группа {0}',
    'group.exportName': 'Результаты групп',
    'team.title': 'Команды',
    'team.subtitle': 'Авто-создание команд по размеру',
    'team.perTeam': 'Размер',
    'team.autoTeam': 'Авто команды',
    'team.emptyTitle': 'Нажмите «Авто команды»',
    'team.emptyDesc': 'Задайте размер, затем распределите',
    'team.namePrefix': 'Команда {0}',
    'team.exportName': 'Результаты команд',
    'toolkit.title': 'Инструменты',
    'cmd.title': '📢 Командные карточки',
    'cmd.inputPlaceholder': 'Тема команды, напр.: Дебаты',
    'cmd.searching': 'Поиск...',
    'cmd.searchBadge': 'Найти значок',
    'cmd.escOrClick': 'ESC или клик для выхода',
    'cmd.quiet': 'Тишина',
    'cmd.discuss': 'Обсуждение',
    'cmd.independent': 'Самостоятельно',
    'cmd.pairTalk': 'Работа в парах',
    'cmd.listen': 'Слушайте',
    'cmd.raiseHand': 'Поднимите руку',
    'qr.title': 'Генератор QR',
    'qr.placeholder': 'Введите URL...',
    'qr.scanTip': '📱 Сканируйте телефоном',
    'qr.emptyTip': 'Введите URL для генерации QR',
    'noise.title': '🔊 Шумомер',
    'noise.level': 'Громкость',
    'noise.quiet': 'Тихо',
    'noise.loud': 'Громко',
    'noise.threshold': 'Порог',
    'noise.peak': 'Пик',
    'noise.tooLoud': 'Слишком громко! Тише!',
    'noise.start': 'Начать',
    'noise.stop': 'Остановить',
    'assign.title': '🎯 Распределитель',
    'assign.inputPlaceholder': 'Название задания...',
    'assign.info': '{0} заданий, {1} учеников',
    'assign.go': 'Распределить',
    'assign.assigning': 'Распределение...',
    'score.title': '🏆 Табло',
    'score.addPlaceholder': 'Имя или команда...',
    'score.step': 'Шаг',
    'score.empty': 'Добавьте участников',
    'score.resetAll': 'Сбросить',
    'lottery.title': '🎲 Случайное / Лотерея',
    'lottery.modeNumber': 'Число',
    'lottery.modeLottery': 'Лотерея',
    'lottery.min': 'Мин',
    'lottery.max': 'Макс',
    'lottery.roll': 'Генерировать',
    'lottery.rolling': 'Генерация...',
    'lottery.draw': 'Тянуть',
    'lottery.drawing': 'Тянем...',
    'lottery.itemsPlaceholder': 'По одному на строку...',
    'lottery.reset': 'Очистить',
    'timer.title': '⏳ Таймер',
    'timer.start': 'Старт',
    'timer.pause': 'Пауза',
    'timer.reset': 'Сброс',
    'timer.timeUp': 'Время вышло!',
    'timer.enableReminder': 'Напоминание',
    'timer.reminderTime': 'Время',
    'timer.secondsBefore': 'с до',
    'timer.voiceAnnounce': 'Голос',
    'timer.reminderSettings': '⏰ Настройки',
    'timer.reminderBefore': 'с напоминание',
    'timer.voiceOnly': '(голос)',
    'timer.colorOnly': '(только цвет)',
    'timer.secondsLeft': '⏰ Осталось {0} с',
    'timer.exitFullscreen': 'Выход (ESC)',
    'timer.ttsReminder': 'Осталось {0} секунд',
    'checkin.title': 'Отметка',
    'checkin.desc': 'Студенты сканируют QR для отметки',
    'checkin.duration': 'Длительность',
    'checkin.minutes': 'мин',
    'checkin.start': 'Начать',
    'checkin.history': 'История',
    'checkin.historyTitle': 'История отметок',
    'checkin.back': 'Назад',
    'checkin.noHistory': 'Нет записей',
    'checkin.createFailed': 'Ошибка создания',
    'checkin.started': 'Отметка началась',
    'checkin.startedDesc': 'Длительность: {0} мин',
    'checkin.ended': 'Отметка завершена',
    'checkin.endCheckin': 'Завершить',
    'checkin.checkedIn': 'Отмечен',
    'checkin.unchecked': 'Не отмечен',
    'checkin.unknown': 'Неизвестно',
    'checkin.leave': 'Отсутствует',
    'checkin.absent': 'Прогул',
    'checkin.scanToCheckin': 'Сканируйте для отметки',
    'checkin.stats': 'Статистика',
    'checkin.rate': 'Процент',
    'checkin.timeStats': 'Время отметки',
    'checkin.avgTime': 'Среднее',
    'checkin.fastest': 'Быстро',
    'checkin.slowest': 'Медленно',
    'checkin.exportName': 'Запись отметок',
    'checkin.secondsUnit': 'с',
    'checkin.minuteSecond': '{0}м{1}с',
    'seat.title': 'Рассадка',
    'seat.subtitle': 'Настраиваемая схема рассадки',
    'seat.rows': 'Ряды',
    'seat.cols': 'Столб.',
    'seat.groups': 'Группы',
    'seat.skipRow': 'Через ряд',
    'seat.skipCol': 'Через столб.',
    'seat.startFrom': 'Начало',
    'seat.fromDoor': 'От двери',
    'seat.fromWindow': 'От окна',
    'seat.autoSeat': 'Авто рассадка',
    'seat.colAisle': 'Проход стлб.',
    'seat.rowAisle': 'Проход ряд',
    'seat.checkin': 'Отметка',
    'seat.exportName': 'Схема мест',
    'seat.emptyTitle': 'Выберите режим и нажмите «Авто рассадка»',
    'seat.emptyDesc': 'Несколько режимов, перетаскивание мест',
    'seat.podium': '🏫 Кафедра',
    'seat.window': 'Окно',
    'seat.door': 'Дверь',
    'seat.windowSide': 'Сторона окна',
    'seat.doorSide': 'Сторона двери',
    'seat.swapDoorWindow': 'Поменять стороны',
    'seat.empty': '—',
    'seat.legend': '💡 Перетаскивание · Клик для отключения · Двойной клик для удаления',
    'seat.colLabel': 'Ст. {0}',
    'seat.rowLabel': 'Ряд {0}',
    'seatMode.verticalS': 'Верт. S',
    'seatMode.horizontalS': 'Гор. S',
    'seatMode.groupCol': 'Группа/Ст.',
    'seatMode.groupRow': 'Группа/Ряд',
    'seatMode.smartCluster': 'Кластер',
    'seatMode.random': 'Случайно',
    'seatMode.exam': 'Экзамен',
    'scene.classroom': '🏫 Класс',
    'scene.classroomDesc': 'Сетка',
    'scene.smartClassroom': '⭕ Смарт класс',
    'scene.smartClassroomDesc': 'Круглые столы',
    'scene.conference': '📋 Конференция',
    'scene.conferenceDesc': 'Длинный стол',
    'scene.concertHall': '🎵 Конц. зал',
    'scene.concertHallDesc': 'Полукруг',
    'scene.banquet': '🎪 Банкет',
    'scene.banquetDesc': 'Круглые столы',
    'scene.computerLab': '💻 Компьютерный класс',
    'scene.computerLabDesc': 'Длинные столы',
    'library.title': 'Библиотека',
    'library.import': 'Импорт',
    'library.export': 'Экспорт',
    'library.addCollege': 'Добавить...',
    'library.addClass': 'Добавить класс...',
    'library.noColleges': 'Нет факультетов',
    'library.noCollegesHint': 'Добавьте или импортируйте',
    'library.selectClass': 'Выберите класс',
    'library.loadToList': 'Загрузить',
    'library.studentNumber': 'Номер',
    'library.studentName': 'Имя',
    'library.confirmImport': 'Подтвердить',
    'library.cancel': 'Отмена',
    'library.importSuccess': 'Импорт успешен',
    'library.importPreview': 'Предпросмотр',
    'library.college': 'Факультет',
    'library.class': 'Класс',
    'library.append': 'Добавить',
    'library.overwrite': 'Заменить',
    'library.existingClassHandling': 'Существующий класс:',
    'export.namePlaceholder': 'Имя экспорта ({0})',
    'export.exported': 'Экспортировано: {0}',
    'export.failed': 'Ошибка экспорта',
    'export.retry': 'Попробуйте снова',
    'auth.appTitle': 'TeachMate',
    'auth.loginTitle': 'Вход',
    'auth.signupTitle': 'Регистрация',
    'auth.forgotTitle': 'Сброс пароля',
    'auth.emailPlaceholder': 'Email',
    'auth.passwordPlaceholder': 'Пароль',
    'auth.nicknamePlaceholder': 'Псевдоним',
    'auth.login': 'Войти',
    'auth.signup': 'Зарегистрироваться',
    'auth.loginFailed': 'Ошибка входа',
    'auth.signupFailed': 'Ошибка регистрации',
    'auth.signupSuccess': 'Регистрация успешна',
    'auth.signupSuccessDesc': 'Проверьте email. Требуется одобрение администратора.',
    'auth.signupNote': 'Требуется одобрение администратора',
    'auth.noAccount': 'Нет аккаунта? Регистрация',
    'auth.hasAccount': 'Есть аккаунт? Вход',
    'auth.forgotPassword': 'Забыли пароль',
    'auth.backToLogin': 'Назад к входу',
    'auth.sendReset': 'Отправить',
    'auth.sending': 'Отправка...',
    'auth.pleaseWait': 'Подождите...',
    'auth.guestContinue': 'Продолжить как гость',
    'auth.pendingTitle': 'Ожидание',
    'auth.pendingDesc': 'Ваш аккаунт ожидает одобрения.',
    'auth.pendingStatus': 'Ожидание',
    'auth.guestBtn': 'Как гость',
    'auth.rejectedTitle': 'Отклонено',
    'auth.rejectedDesc': 'Заявка отклонена. Свяжитесь с администратором.',
    'reset.title': 'Новый пароль',
    'reset.placeholder': 'Новый пароль (мин. 6 символов)',
    'reset.confirm': 'Подтвердить',
    'reset.resetting': 'Сброс...',
    'reset.invalidLink': 'Недействительная ссылка',
    'reset.backToLogin': 'Назад к входу',
    'reset.minLength': 'Минимум 6 символов',
    'reset.failed': 'Ошибка сброса',
    'reset.success': 'Пароль сброшен',
    'admin.title': 'Управление',
    'admin.back': 'Назад',
    'admin.searchPlaceholder': 'Поиск...',
    'admin.all': 'Все',
    'admin.pending': 'Ожидание',
    'admin.approved': 'Одобрено',
    'admin.rejected': 'Отклонено',
    'admin.selected': 'Выбрано: {0}',
    'admin.batchApprove': 'Одобрить',
    'admin.batchReject': 'Отклонить',
    'admin.approve': 'Одобрить',
    'admin.reject': 'Отклонить',
    'admin.changeToApprove': 'Одобрить',
    'admin.selectAll': 'Выбрать все',
    'admin.noPending': 'Нет ожидающих',
    'admin.operationFailed': 'Ошибка',
    'admin.batchResult': '{0}: {1} пользователей',
    'checkinPage.loading': 'Загрузка...',
    'checkinPage.expired': 'Отметка завершена',
    'checkinPage.expiredDesc': 'Сессия истекла',
    'checkinPage.success': 'Отметка успешна!',
    'checkinPage.completed': '{0} отмечен',
    'checkinPage.title': 'Отметка',
    'checkinPage.desc': 'Введите имя',
    'checkinPage.namePlaceholder': 'Ваше имя',
    'checkinPage.checkinBtn': 'Отметиться',
    'checkinPage.checking': 'Отметка...',
    'checkinPage.failed': 'Ошибка, попробуйте снова',
    'discuss.topicNotFound': 'Тема не найдена',
    'discuss.loading': 'Загрузка...',
    'discuss.enterNickname': 'Введите псевдоним',
    'discuss.nicknamePlaceholder': 'Ваш псевдоним...',
    'discuss.enterDiscussion': 'Присоединиться 🚀',
    'discuss.noRegister': '🔒 Регистрация не нужна',
    'discuss.topic': '💬 Тема',
    'discuss.nickname': 'Псевдоним',
    'discuss.edit': 'Изменить',
    'discuss.recentBarrage': 'Последние сообщения',
    'discuss.inputBarrage': 'Введите сообщение (макс 50)...',
    'discuss.sendFailed': 'Ошибка отправки',
    'discuss.send': 'Отправить 🚀',
    'discuss.sendingBtn': 'Отправка...',
    'discuss.sendSuccess': '✅ Отправлено!',
    'discuss.dataPrivacy': '🔒 Данные только для обсуждения',
    'notFound.title': 'Страница не найдена',
    'notFound.back': 'На главную',
    'seatCheckin.title': 'Отметка мест',
    'seatCheckin.desc': 'Введите имя',
    'seatCheckin.namePlaceholder': 'Ваше имя',
    'seatCheckin.confirm': 'Подтвердить',
    'seatCheckin.checking': 'Отметка...',
    'seatCheckin.loading': 'Загрузка...',
    'seatCheckin.notFound': 'Сессия не найдена',
    'seatCheckin.success': 'Успешно!',
    'seatCheckinDialog.title': 'Отметка мест',
    'seatCheckinDialog.desc': 'QR-код для поиска своего места.',
    'seatCheckinDialog.generate': 'Создать QR',
    'seatCheckinDialog.generating': 'Создание...',
    'seatCheckinDialog.checkedIn': 'Отмечен',
    'go.invalidLink': 'Недействительная ссылка',
    'go.redirecting': 'Перенаправление...',
    'go.openInBrowser': 'Открыть в браузере',
    'go.wechatWarning': 'Вы используете WeChat. Откройте в браузере.',
    'go.recommended': 'Рекомендуется',
    'go.recommendedDesc': 'Нажмите ⋯ → «Открыть в браузере»',
    'go.copyLink': 'Копировать',
    'go.copied': 'Скопировано!',
    'go.tryDirect': 'Попробовать напрямую',
    'wechat.warning': 'Вы используете WeChat. Нажмите ⋯ → «Открыть в браузере».',
    'common.save': 'Сохранить',
    'common.cancel': 'Отмена',
    'common.loading': 'Загрузка...',
    'board.title': 'Доска идей',
    'board.create': 'Создать доску',
    'board.myBoards': 'Мои доски',
    'board.noBoards': 'Нет досок',
    'board.emptyHint': 'Создайте доску, чтобы ученики делились идеями через карточки',
    'board.boardTitle': 'Название',
    'board.boardDesc': 'Описание',
    'board.delete': 'Удалить',
    'board.deleteConfirm': 'Удалить доску и все карточки?',
    'board.settings': 'Настройки',
    'board.lock': 'Заблокировать',
    'board.unlock': 'Разблокировать',
    'board.locked': 'Заблокирована',
    'board.moderation': 'Модерация',
    'board.moderationOn': 'Модерация вкл.',
    'board.moderationOff': 'Модерация выкл.',
    'board.bannedWords': 'Запрещённые слова',
    'board.viewWall': 'Стена',
    'board.viewKanban': 'Канбан',
    'board.viewTimeline': 'Лента',
    'board.viewCanvas': 'Холст',
    'board.addCard': 'Добавить',
    'board.cardContent': 'Содержание...',
    'board.cardColor': 'Цвет',
    'board.cardUrl': 'Ссылка',
    'board.nickname': 'Псевдоним',
    'board.nicknamePlaceholder': 'Введите имя...',
    'board.submit': 'Отправить',
    'board.submitting': 'Отправка...',
    'board.submitSuccess': 'Отправлено!',
    'board.submitPage': 'Добавить карточку',
    'board.joinBoard': 'Присоединиться',
    'board.scanToJoin': 'Сканируйте QR',
    'board.pin': 'Закрепить',
    'board.unpin': 'Открепить',
    'board.approve': 'Одобрить',
    'board.reject': 'Отклонить',
    'board.pending': 'На проверке',
    'board.pendingCount': '{0} на проверке',
    'board.likes': 'Нравится',
    'board.comments': 'Комментарии',
    'board.addComment': 'Комментарий...',
    'board.export': 'Экспорт',
    'board.exportCSV': 'Экспорт CSV',
    'board.exportPNG': 'Скриншот',
    'board.pptMode': 'Слайд-шоу',
    'board.wordCloud': 'Облако слов',
    'board.wordCloudRefresh': 'Обновить',
    'board.wordCloudEmpty': 'Недостаточно контента для облака слов',
    'board.wordCloudTheme': 'Тема',
    'board.smartReport': 'Умный отчёт',
    'board.reportGenerate': 'Создать отчёт',
    'board.reportGenerating': 'ИИ анализирует...',
    'board.reportRegenerate': 'Пересоздать',
    'board.reportNoCards': 'Нет карточек для анализа',
    'board.reportError': 'Не удалось создать отчёт',
    'board.reportPrompt': 'Нажмите «Создать отчёт» для начала ИИ-анализа',
    'board.reportPromptSub': 'Анализ содержимого {0} карточек',
    'board.reportCardCount': 'карточек',
    'board.reportStreaming': 'Генерация...',
    'ai.guestLimitReached': 'Дневной лимит ИИ исчерпан. Войдите для неограниченного доступа',
    'ai.guestRemaining': 'Гостевой ИИ: {0}/{1} осталось сегодня. Войдите для безлимита',
    'board.pptPrev': 'Назад',
    'board.pptNext': 'Далее',
    'board.pptExit': 'Выйти',
    'board.pptSlide': '{0} / {1}',
    'board.qrcode': 'QR-код',
    'board.shareLink': 'Поделиться',
    'board.anonymous': 'Аноним',
    'board.cardTypeText': 'Текст',
    'board.cardTypeImage': 'Изображение',
    'board.cardTypeUrl': 'Ссылка',
    'board.columns': 'Колонки',
    'board.addColumn': 'Добавить колонку',
    'board.blockedWord': 'Содержимое на проверке',
    'board.lockedMsg': 'Доска заблокирована',
    'board.back': 'К доскам',
    'board.uploadImage': 'Загрузить',
    'board.uploadFile': 'Загрузить файл',
    'board.uploading': 'Загрузка...',
    'board.downloadFile': 'Скачать',
    'board.viewFile': 'Открыть',
    'board.commentSend': 'Отправить',
    'board.noComments': 'Нет комментариев',
    'board.cloudSync': '☁️ Синхронизировано',
  },
  ja: {
    'app.title': 'TeachMate',
    'app.subtitle': 'TeachMate |--洛陽理工学院--| limeng@lit.edu.cn',
    'tab.random': 'ランダム指名',
    'tab.groups': 'グループ',
    'tab.teams': 'チーム',
    'tab.seats': '座席',
    'tab.checkin': '出席確認',
    'tab.board': 'ボード',
    'tab.toolkit': 'ツールボックス',
    'ext.ai': 'AIアシスタント',
    'ext.idea': 'IdeaVas',
    'ext.tip': '同じメールでログイン',
    'sidebar.current': '📋 現在の名簿',
    'sidebar.library': '🏫 クラスライブラリ',
    'sidebar.studentList': '学生名簿',
    'sidebar.noStudents': '学生がいません。名簿をインポートしてください。',
    'sidebar.addStudent': '学生を追加...',
    'sidebar.import': 'インポート',
    'sidebar.clear': 'クリア',
    'sidebar.importTitle': '学生名簿のインポート',
    'sidebar.importPaste': '名前を貼り付け（1行に1人）：',
    'sidebar.importConfirm': 'インポート確認',
    'sidebar.importFile': 'またはTXTファイルをアップロード：',
    'sidebar.expandPanel': 'パネルを展開',
    'sidebar.collapsePanel': 'パネルを折りたたむ',
    'sidebar.persons': '人',
    'header.login': 'ログイン',
    'header.admin': 'ユーザー管理',
    'header.loading': '読み込み中...',
    'settings.title': '設定',
    'settings.theme': '🎨 テーマ',
    'settings.font': 'フォント',
    'settings.fontSize': 'フォントサイズ',
    'settings.fontSmall': '小',
    'settings.fontLarge': '大',
    'settings.nickname': 'ニックネーム',
    'settings.nicknamePlaceholder': 'ニックネームを設定',
    'settings.save': '保存',
    'settings.saved': '保存しました',
    'settings.logout': 'ログアウト',
    'settings.loggedOut': 'ログアウトしました',
    'settings.profile': 'プロフィール',
    'settings.email': 'メール',
    'settings.cloudSync': '☁️ クラウド同期済み',
    'settings.localOnly': '🔒 ローカル保存のみ',
    'random.sound': '効果音',
    'random.voice': '音声',
    'random.noRepeat': '重複なし',
    'random.popup': 'ポップアップ',
    'random.seconds': '秒',
    'random.title': 'ランダム指名',
    'random.wheelMode': 'ルーレット',
    'random.rollerMode': 'ローラーモード',
    'random.persons': '人',
    'random.roll': '回転',
    'random.pressToStop': '任意のキーで停止...',
    'random.selected': '選択',
    'random.picked': '選択済み',
    'random.remaining': '残り',
    'random.reset': 'リセット',
    'random.clearList': 'クリア',
    'random.pickedList': '選択リスト',
    'random.clickToClose': 'ESCまたは空白をクリックで閉じる',
    'random.clickAnywhereClose': 'クリックで閉じる',
    'random.spinning': '回転中（クリックで停止）',
    'random.spin': '回転',
    'random.clickWheelStop': 'クリックで停止...',
    'dice.title': '🎲 スマートダイス',
    'dice.subtitle': '(グループ/チームベース)',
    'dice.mode': 'モード',
    'dice.basedOnGroup': 'グループ',
    'dice.basedOnTeam': 'チーム',
    'dice.throw': '🎲 振る',
    'dice.group': 'グループ',
    'dice.member': 'メンバー',
    'dice.groupResult': 'グループ{0} メンバー{1}',
    'dice.groupDice': '(グループ{0}→ダイス{1}個)',
    'group.title': 'グループ分け',
    'group.subtitle': '{0}名を自動グループ分け',
    'group.count': 'グループ数',
    'group.autoGroup': '自動グループ',
    'group.emptyTitle': '「自動グループ」をクリック',
    'group.emptyDesc': '2-10グループ、カスタム名、リーダー指定、ドラッグ調整',
    'group.namePrefix': 'グループ{0}',
    'group.exportName': 'グループ結果',
    'team.title': 'チーム編成',
    'team.subtitle': 'チームサイズ指定で自動編成',
    'team.perTeam': 'チーム人数',
    'team.autoTeam': '自動チーム',
    'team.emptyTitle': '「自動チーム」をクリック',
    'team.emptyDesc': 'サイズを設定してランダム配分',
    'team.namePrefix': 'チーム{0}',
    'team.exportName': 'チーム結果',
    'toolkit.title': '教室ツールボックス',
    'cmd.title': '📢 指示カード',
    'cmd.inputPlaceholder': '指示テーマを入力、例：ディベート',
    'cmd.searching': '検索中...',
    'cmd.searchBadge': 'バッジ検索',
    'cmd.escOrClick': 'ESCまたはクリックで退出',
    'cmd.quiet': '静かに',
    'cmd.discuss': 'グループ討論',
    'cmd.independent': '自主学習',
    'cmd.pairTalk': 'ペアワーク',
    'cmd.listen': '注意して聞く',
    'cmd.raiseHand': '手を挙げる',
    'qr.title': 'QRコード生成',
    'qr.placeholder': 'URLを入力...',
    'qr.scanTip': '📱 スマホでスキャン',
    'qr.emptyTip': 'URLを入力してQRコード生成',
    'noise.title': '🔊 騒音検出',
    'noise.level': '音量',
    'noise.quiet': '静か',
    'noise.loud': 'うるさい',
    'noise.threshold': '警告しきい値',
    'noise.peak': 'ピーク',
    'noise.tooLoud': 'うるさい！静かに！',
    'noise.start': '検出開始',
    'noise.stop': '停止',
    'assign.title': '🎯 ランダム割当',
    'assign.inputPlaceholder': 'タスク名を入力...',
    'assign.info': '{0}個のタスク、{1}人',
    'assign.go': 'ランダム割当',
    'assign.assigning': '割当中...',
    'score.title': '🏆 スコアボード',
    'score.addPlaceholder': '名前またはチーム...',
    'score.step': 'ステップ',
    'score.empty': '参加者を追加してください',
    'score.resetAll': 'リセット',
    'lottery.title': '🎲 乱数/くじ引き',
    'lottery.modeNumber': '乱数',
    'lottery.modeLottery': 'くじ引き',
    'lottery.min': '最小',
    'lottery.max': '最大',
    'lottery.roll': '生成',
    'lottery.rolling': '生成中...',
    'lottery.draw': '引く',
    'lottery.drawing': '引いています...',
    'lottery.itemsPlaceholder': '1行に1つ...',
    'lottery.reset': 'クリア',
    'timer.title': '⏳ カウントダウン',
    'timer.start': '開始',
    'timer.pause': '一時停止',
    'timer.reset': 'リセット',
    'timer.timeUp': '時間です！',
    'timer.enableReminder': 'リマインダー',
    'timer.reminderTime': '時間',
    'timer.secondsBefore': '秒前',
    'timer.voiceAnnounce': '音声',
    'timer.reminderSettings': '⏰ リマインダー設定',
    'timer.reminderBefore': '秒前リマインダー',
    'timer.voiceOnly': '(音声)',
    'timer.colorOnly': '(色のみ)',
    'timer.secondsLeft': '⏰ 残り{0}秒',
    'timer.exitFullscreen': '全画面終了 (ESC)',
    'timer.ttsReminder': '残り{0}秒です',
    'checkin.title': '出席確認',
    'checkin.desc': 'QRコードで出席確認',
    'checkin.duration': '時間',
    'checkin.minutes': '分',
    'checkin.start': '開始',
    'checkin.history': '履歴',
    'checkin.historyTitle': '出席履歴',
    'checkin.back': '戻る',
    'checkin.noHistory': '記録なし',
    'checkin.started': '出席確認開始',
    'checkin.startedDesc': '時間: {0}分',
    'checkin.ended': '出席確認終了',
    'checkin.endCheckin': '終了',
    'checkin.checkedIn': '出席',
    'checkin.unchecked': '未出席',
    'checkin.unknown': '不明',
    'checkin.leave': '欠席',
    'checkin.absent': '欠席',
    'checkin.scanToCheckin': 'スキャンして出席',
    'checkin.stats': '出席統計',
    'checkin.rate': '出席率',
    'checkin.timeStats': '時間統計',
    'checkin.avgTime': '平均',
    'checkin.fastest': '最速',
    'checkin.slowest': '最遅',
    'checkin.exportName': '出席記録',
    'checkin.secondsUnit': '秒',
    'checkin.minuteSecond': '{0}分{1}秒',
    'seat.title': '座席配置',
    'seat.subtitle': 'カスタムレイアウト、複数モード',
    'seat.rows': '行',
    'seat.cols': '列',
    'seat.groups': 'グループ',
    'seat.skipRow': '行飛ばし',
    'seat.skipCol': '列飛ばし',
    'seat.startFrom': '開始',
    'seat.fromDoor': 'ドア側から',
    'seat.fromWindow': '窓側から',
    'seat.autoSeat': '自動配置',
    'seat.colAisle': '列通路',
    'seat.rowAisle': '行通路',
    'seat.checkin': '出席',
    'seat.exportName': '座席表',
    'seat.emptyTitle': 'モードを選んで「自動配置」',
    'seat.emptyDesc': '複数モード、ドラッグで交換',
    'seat.podium': '🏫 教壇',
    'seat.window': '窓',
    'seat.door': 'ドア',
    'seat.windowSide': '窓側',
    'seat.doorSide': 'ドア側',
    'seat.swapDoorWindow': 'ドア/窓を入れ替え',
    'seat.empty': '空',
    'seat.legend': '💡 ドラッグで交換 · クリックで無効化 · ダブルクリックで通路削除',
    'seat.colLabel': '{0}列',
    'seat.rowLabel': '{0}行',
    'seatMode.verticalS': '縦S字',
    'seatMode.horizontalS': '横S字',
    'seatMode.groupCol': 'グループ/列',
    'seatMode.groupRow': 'グループ/行',
    'seatMode.smartCluster': 'クラスター',
    'seatMode.random': 'ランダム',
    'seatMode.exam': '試験',
    'scene.classroom': '🏫 教室',
    'scene.classroomDesc': 'グリッド配置',
    'scene.smartClassroom': '⭕ スマート教室',
    'scene.smartClassroomDesc': '円卓グループ',
    'scene.conference': '📋 会議室',
    'scene.conferenceDesc': '会議テーブル',
    'scene.concertHall': '🎵 コンサートホール',
    'scene.concertHallDesc': '半円形',
    'scene.banquet': '🎪 宴会場',
    'scene.banquetDesc': '円卓',
    'scene.computerLab': '💻 PC教室',
    'scene.computerLabDesc': '長テーブル対面',
    'library.title': 'クラスライブラリ',
    'library.import': 'インポート',
    'library.export': 'エクスポート',
    'library.addCollege': '学部を追加...',
    'library.addClass': 'クラスを追加...',
    'library.noColleges': '学部なし',
    'library.noCollegesHint': '追加またはインポート',
    'library.selectClass': 'クラスを選択',
    'library.loadToList': '名簿に読込',
    'library.studentNumber': '番号',
    'library.studentName': '名前',
    'library.confirmImport': '確認',
    'library.cancel': 'キャンセル',
    'library.importSuccess': 'インポート成功',
    'library.importPreview': 'プレビュー',
    'library.college': '学部',
    'library.class': 'クラス',
    'library.append': '追加',
    'library.overwrite': '上書き',
    'library.existingClassHandling': '既存クラス:',
    'export.namePlaceholder': 'エクスポート名 ({0})',
    'export.exported': '{0}としてエクスポート',
    'export.failed': 'エクスポート失敗',
    'export.retry': 'もう一度お試しください',
    'auth.appTitle': 'TeachMate',
    'auth.loginTitle': 'ログイン',
    'auth.signupTitle': 'アカウント作成',
    'auth.forgotTitle': 'パスワードリセット',
    'auth.emailPlaceholder': 'メールアドレス',
    'auth.passwordPlaceholder': 'パスワード',
    'auth.nicknamePlaceholder': 'ニックネーム（任意）',
    'auth.login': 'ログイン',
    'auth.signup': '登録',
    'auth.loginFailed': 'ログイン失敗',
    'auth.signupFailed': '登録失敗',
    'auth.signupSuccess': '登録成功',
    'auth.signupSuccessDesc': 'メールを確認してください。管理者承認後に全機能利用可能。',
    'auth.signupNote': '管理者承認が必要です',
    'auth.noAccount': 'アカウントがない？登録',
    'auth.hasAccount': 'アカウントがある？ログイン',
    'auth.forgotPassword': 'パスワードを忘れた',
    'auth.backToLogin': 'ログインに戻る',
    'auth.sendReset': 'リセットメール送信',
    'auth.sending': '送信中...',
    'auth.pleaseWait': 'お待ちください...',
    'auth.guestContinue': 'ゲストとして続ける',
    'auth.pendingTitle': '承認待ち',
    'auth.pendingDesc': 'アカウントは承認待ちです。',
    'auth.pendingStatus': '審査中',
    'auth.guestBtn': 'ゲストとして続ける',
    'auth.rejectedTitle': '承認されませんでした',
    'auth.rejectedDesc': '申請が承認されませんでした。管理者にお問い合わせください。',
    'reset.title': '新しいパスワード',
    'reset.placeholder': '新しいパスワード（6文字以上）',
    'reset.confirm': '確認',
    'reset.resetting': 'リセット中...',
    'reset.invalidLink': '無効なリンク',
    'reset.backToLogin': 'ログインに戻る',
    'reset.minLength': 'パスワードは6文字以上',
    'reset.failed': 'リセット失敗',
    'reset.success': 'パスワードリセット完了',
    'admin.title': 'ユーザー管理',
    'admin.back': '戻る',
    'admin.searchPlaceholder': '検索...',
    'admin.all': '全て',
    'admin.pending': '承認待ち',
    'admin.approved': '承認済み',
    'admin.rejected': '拒否済み',
    'admin.selected': '{0}人選択',
    'admin.batchApprove': '一括承認',
    'admin.batchReject': '一括拒否',
    'admin.approve': '承認',
    'admin.reject': '拒否',
    'admin.changeToApprove': '承認に変更',
    'admin.selectAll': '全選択',
    'admin.noPending': '承認待ちなし',
    'admin.operationFailed': '操作失敗',
    'admin.batchResult': '{1}人を{0}',
    'checkinPage.loading': '読み込み中...',
    'checkinPage.expired': '出席確認終了',
    'checkinPage.expiredDesc': 'このセッションは終了しました',
    'checkinPage.success': '出席確認完了！',
    'checkinPage.completed': '{0}の出席を確認しました',
    'checkinPage.title': '出席確認',
    'checkinPage.desc': '名前を入力してください',
    'checkinPage.namePlaceholder': '名前を入力',
    'checkinPage.checkinBtn': '出席確認',
    'checkinPage.checking': '確認中...',
    'checkinPage.failed': '失敗しました。もう一度お試しください。',
    'discuss.topicNotFound': 'トピックが見つかりません',
    'discuss.loading': '読み込み中...',
    'discuss.enterNickname': 'ニックネームで参加',
    'discuss.nicknamePlaceholder': 'ニックネーム...',
    'discuss.enterDiscussion': '参加する 🚀',
    'discuss.noRegister': '🔒 登録不要',
    'discuss.topic': '💬 トピック',
    'discuss.nickname': 'ニックネーム',
    'discuss.edit': '編集',
    'discuss.recentBarrage': '最新メッセージ',
    'discuss.inputBarrage': 'メッセージを入力（最大50文字）...',
    'discuss.sendFailed': '送信失敗',
    'discuss.send': '送信 🚀',
    'discuss.sendingBtn': '送信中...',
    'discuss.sendSuccess': '✅ 送信成功！',
    'discuss.dataPrivacy': '🔒 データは教室内のみ',
    'notFound.title': 'ページが見つかりません',
    'notFound.back': 'ホームに戻る',
    'seatCheckin.title': '座席確認',
    'seatCheckin.desc': '名前を入力して座席を確認',
    'seatCheckin.namePlaceholder': '名前を入力',
    'seatCheckin.confirm': '確認',
    'seatCheckin.checking': '確認中...',
    'seatCheckin.loading': '読み込み中...',
    'seatCheckin.notFound': 'セッションが見つかりません',
    'seatCheckin.success': '確認完了！',
    'seatCheckinDialog.title': '座席確認',
    'seatCheckinDialog.desc': 'QRコードで座席を確認',
    'seatCheckinDialog.generate': 'QRコード生成',
    'seatCheckinDialog.generating': '生成中...',
    'seatCheckinDialog.checkedIn': '確認済み',
    'go.invalidLink': '無効なリンク',
    'go.redirecting': 'リダイレクト中...',
    'go.openInBrowser': 'ブラウザで開く',
    'go.wechatWarning': 'WeChatブラウザです。ブラウザで開いてください。',
    'go.recommended': 'おすすめ',
    'go.recommendedDesc': '右上の⋯→「ブラウザで開く」',
    'go.copyLink': 'リンクをコピー',
    'go.copied': 'コピーしました！',
    'go.tryDirect': '直接開く',
    'wechat.warning': 'WeChatブラウザです。⋯→「ブラウザで開く」を選択してください。',
    'common.save': '保存',
    'common.cancel': 'キャンセル',
    'common.loading': '読み込み中...',
    'board.title': 'クリエイティブボード',
    'board.create': 'ボード作成',
    'board.myBoards': 'マイボード',
    'board.noBoards': 'ボードがありません',
    'board.emptyHint': 'ボードを作成して、学生がカードでアイデアを共有できるようにしましょう',
    'board.boardTitle': 'ボード名',
    'board.boardDesc': '説明（任意）',
    'board.delete': '削除',
    'board.deleteConfirm': 'このボードを削除しますか？',
    'board.settings': '設定',
    'board.lock': 'ロック',
    'board.unlock': 'ロック解除',
    'board.locked': 'ロック中',
    'board.moderation': 'モデレーション',
    'board.moderationOn': 'モデレーション有効',
    'board.moderationOff': 'モデレーション無効',
    'board.bannedWords': 'NGワード',
    'board.viewWall': 'ウォール',
    'board.viewKanban': 'カンバン',
    'board.viewTimeline': 'タイムライン',
    'board.viewCanvas': 'キャンバス',
    'board.addCard': 'カード追加',
    'board.cardContent': '内容を入力...',
    'board.cardColor': 'カード色',
    'board.cardUrl': 'URL',
    'board.nickname': 'ニックネーム',
    'board.nicknamePlaceholder': 'ニックネームを入力...',
    'board.submit': '投稿',
    'board.submitting': '投稿中...',
    'board.submitSuccess': '投稿しました！',
    'board.submitPage': 'カード投稿',
    'board.joinBoard': '参加',
    'board.scanToJoin': 'QRコードで参加',
    'board.pin': 'ピン留め',
    'board.unpin': 'ピン解除',
    'board.approve': '承認',
    'board.reject': '却下',
    'board.pending': '審査中',
    'board.pendingCount': '{0} 件審査中',
    'board.likes': 'いいね',
    'board.comments': 'コメント',
    'board.addComment': 'コメント...',
    'board.export': 'エクスポート',
    'board.exportCSV': 'CSV出力',
    'board.exportPNG': 'スクリーンショット',
    'board.pptMode': 'スライドショー',
    'board.wordCloud': 'ワードクラウド',
    'board.wordCloudRefresh': '再生成',
    'board.wordCloudEmpty': 'ワードクラウドを生成するコンテンツが不足しています',
    'board.wordCloudTheme': 'テーマ',
    'board.smartReport': 'スマートレポート',
    'board.reportGenerate': 'レポート生成',
    'board.reportGenerating': 'AI分析中...',
    'board.reportRegenerate': '再生成',
    'board.reportNoCards': 'カードがありません',
    'board.reportError': 'レポート生成に失敗しました',
    'board.reportPrompt': '「レポート生成」をクリックしてAI分析を開始',
    'board.reportPromptSub': '{0}枚のカード内容を分析します',
    'board.reportCardCount': '枚のカード',
    'board.reportStreaming': '生成中...',
    'ai.guestLimitReached': '本日のAI使用回数が上限に達しました。ログインすると無制限に利用できます',
    'ai.guestRemaining': 'ゲストAI使用: 本日残り{0}/{1}回。ログインで無制限',
    'board.pptPrev': '前へ',
    'board.pptNext': '次へ',
    'board.pptExit': '終了',
    'board.pptSlide': '{0} / {1}',
    'board.qrcode': 'QRコード',
    'board.shareLink': '共有リンク',
    'board.anonymous': '匿名',
    'board.cardTypeText': 'テキスト',
    'board.cardTypeImage': '画像',
    'board.cardTypeUrl': 'リンク',
    'board.columns': 'カラム',
    'board.addColumn': 'カラム追加',
    'board.blockedWord': '審査待ち',
    'board.lockedMsg': 'ボードはロック中です',
    'board.back': 'ボード一覧へ',
    'board.uploadImage': '画像アップロード',
    'board.uploadFile': 'ファイルアップロード',
    'board.uploading': 'アップロード中...',
    'board.downloadFile': 'ダウンロード',
    'board.viewFile': 'ファイルを開く',
    'board.commentSend': '送信',
    'board.noComments': 'コメントなし',
    'board.cloudSync': '☁️ クラウド同期済み',
  },
  ko: {
    'app.title': 'TeachMate',
    'app.subtitle': 'TeachMate |--뤄양 공과대학--| limeng@lit.edu.cn',
    'tab.random': '랜덤 선택',
    'tab.groups': '그룹',
    'tab.teams': '팀',
    'tab.seats': '좌석',
    'tab.checkin': '출석',
    'tab.board': '보드',
    'tab.toolkit': '도구함',
    'ext.ai': 'AI 어시스턴트',
    'ext.idea': 'IdeaVas',
    'ext.tip': '같은 이메일로 로그인하세요',
    'sidebar.current': '📋 현재 명단',
    'sidebar.library': '🏫 학급 라이브러리',
    'sidebar.studentList': '학생 명단',
    'sidebar.noStudents': '학생이 없습니다. 명단을 가져오세요.',
    'sidebar.addStudent': '학생 추가...',
    'sidebar.import': '가져오기',
    'sidebar.clear': '비우기',
    'sidebar.importTitle': '학생 명단 가져오기',
    'sidebar.importPaste': '이름 붙여넣기 (줄당 하나):',
    'sidebar.importConfirm': '가져오기 확인',
    'sidebar.importFile': '또는 TXT 파일 업로드:',
    'sidebar.expandPanel': '패널 펼치기',
    'sidebar.collapsePanel': '패널 접기',
    'sidebar.persons': '명',
    'header.login': '로그인',
    'header.admin': '사용자 관리',
    'header.loading': '로딩 중...',
    'settings.title': '설정',
    'settings.theme': '🎨 테마',
    'settings.font': '글꼴',
    'settings.fontSize': '글꼴 크기',
    'settings.fontSmall': '소',
    'settings.fontLarge': '대',
    'settings.nickname': '닉네임',
    'settings.nicknamePlaceholder': '닉네임 설정',
    'settings.save': '저장',
    'settings.saved': '저장됨',
    'settings.logout': '로그아웃',
    'settings.loggedOut': '로그아웃됨',
    'settings.profile': '프로필',
    'settings.email': '이메일',
    'settings.cloudSync': '☁️ 클라우드 동기화 완료',
    'settings.localOnly': '🔒 로컬에만 저장',
    'random.sound': '효과음',
    'random.voice': '음성',
    'random.noRepeat': '중복 없음',
    'random.popup': '팝업',
    'random.seconds': '초',
    'random.title': '랜덤 선택',
    'random.wheelMode': '룰렛',
    'random.rollerMode': '롤러 모드',
    'random.persons': '명',
    'random.roll': '굴리기',
    'random.pressToStop': '아무 키나 누르면 정지...',
    'random.selected': '선택됨',
    'random.picked': '선택됨',
    'random.remaining': '남은',
    'random.reset': '초기화',
    'random.clearList': '비우기',
    'random.pickedList': '선택 목록',
    'random.clickToClose': 'ESC 또는 빈 곳 클릭으로 닫기',
    'random.clickAnywhereClose': '아무 곳이나 클릭',
    'random.spinning': '회전 중 (클릭으로 정지)',
    'random.spin': '회전',
    'random.clickWheelStop': '클릭으로 정지...',
    'dice.title': '🎲 스마트 주사위',
    'dice.subtitle': '(그룹/팀 기반)',
    'dice.mode': '모드',
    'dice.basedOnGroup': '그룹 기반',
    'dice.basedOnTeam': '팀 기반',
    'dice.throw': '🎲 던지기',
    'dice.group': '그룹',
    'dice.member': '멤버',
    'dice.groupResult': '그룹 {0} 멤버 {1}',
    'dice.groupDice': '(그룹 {0} → 주사위 {1}개)',
    'group.title': '그룹 나누기',
    'group.subtitle': '{0}명 학생을 자동 그룹 분할',
    'group.count': '그룹 수',
    'group.autoGroup': '자동 그룹',
    'group.emptyTitle': '「자동 그룹」을 클릭하세요',
    'group.emptyDesc': '2-10 그룹, 커스텀 이름, 리더 지정, 드래그 조정',
    'group.namePrefix': '그룹 {0}',
    'group.exportName': '그룹 결과',
    'team.title': '팀 편성',
    'team.subtitle': '팀 크기 지정 후 자동 편성',
    'team.perTeam': '팀당 인원',
    'team.autoTeam': '자동 팀',
    'team.emptyTitle': '「자동 팀」을 클릭하세요',
    'team.emptyDesc': '크기 설정 후 랜덤 배정, 드래그 조정',
    'team.namePrefix': '팀 {0}',
    'team.exportName': '팀 결과',
    'toolkit.title': '교실 도구함',
    'cmd.title': '📢 교실 지시 카드',
    'cmd.inputPlaceholder': '주제 입력, 예: 토론',
    'cmd.searching': '검색 중...',
    'cmd.searchBadge': '배지 검색',
    'cmd.escOrClick': 'ESC 또는 클릭으로 종료',
    'cmd.quiet': '조용히',
    'cmd.discuss': '그룹 토론',
    'cmd.independent': '독립 학습',
    'cmd.pairTalk': '짝 대화',
    'cmd.listen': '경청하기',
    'cmd.raiseHand': '손 들기',
    'qr.title': 'QR코드 생성',
    'qr.placeholder': 'URL 입력...',
    'qr.scanTip': '📱 스마트폰으로 스캔',
    'qr.emptyTip': 'URL을 입력하면 QR코드 생성',
    'noise.title': '🔊 소음 감지기',
    'noise.level': '음량',
    'noise.quiet': '조용',
    'noise.loud': '시끄러움',
    'noise.threshold': '경고 임계값',
    'noise.peak': '최대',
    'noise.tooLoud': '너무 시끄러워요! 조용히!',
    'noise.start': '감지 시작',
    'noise.stop': '중지',
    'assign.title': '🎯 랜덤 배정',
    'assign.inputPlaceholder': '과제 이름 입력...',
    'assign.info': '{0}개 과제, {1}명 학생',
    'assign.go': '랜덤 배정',
    'assign.assigning': '배정 중...',
    'score.title': '🏆 점수판',
    'score.addPlaceholder': '이름 또는 팀...',
    'score.step': '단위',
    'score.empty': '참가자를 추가하세요',
    'score.resetAll': '초기화',
    'lottery.title': '🎲 난수/추첨',
    'lottery.modeNumber': '난수',
    'lottery.modeLottery': '추첨',
    'lottery.min': '최소',
    'lottery.max': '최대',
    'lottery.roll': '생성',
    'lottery.rolling': '생성 중...',
    'lottery.draw': '추첨',
    'lottery.drawing': '추첨 중...',
    'lottery.itemsPlaceholder': '한 줄에 하나씩...',
    'lottery.reset': '기록 삭제',
    'timer.title': '⏳ 카운트다운',
    'timer.start': '시작',
    'timer.pause': '일시정지',
    'timer.reset': '초기화',
    'timer.timeUp': '시간 종료!',
    'timer.enableReminder': '알림',
    'timer.reminderTime': '시간',
    'timer.secondsBefore': '초 전',
    'timer.voiceAnnounce': '음성',
    'timer.reminderSettings': '⏰ 알림 설정',
    'timer.reminderBefore': '초 전 알림',
    'timer.voiceOnly': '(음성)',
    'timer.colorOnly': '(색상만)',
    'timer.secondsLeft': '⏰ {0}초 남음',
    'timer.exitFullscreen': '전체화면 종료 (ESC)',
    'timer.ttsReminder': '{0}초 남았습니다',
    'checkin.title': '출석 확인',
    'checkin.desc': 'QR코드로 출석 확인',
    'checkin.duration': '시간',
    'checkin.minutes': '분',
    'checkin.start': '출석 시작',
    'checkin.history': '기록 보기',
    'checkin.historyTitle': '출석 기록',
    'checkin.back': '뒤로',
    'checkin.noHistory': '기록 없음',
    'checkin.started': '출석 시작됨',
    'checkin.startedDesc': '시간: {0}분',
    'checkin.ended': '출석 종료',
    'checkin.endCheckin': '종료',
    'checkin.checkedIn': '출석',
    'checkin.unchecked': '미출석',
    'checkin.unknown': '알 수 없음',
    'checkin.leave': '결석',
    'checkin.absent': '결석',
    'checkin.scanToCheckin': '스캔하여 출석',
    'checkin.stats': '출석 통계',
    'checkin.rate': '출석률',
    'checkin.timeStats': '시간 통계',
    'checkin.avgTime': '평균',
    'checkin.fastest': '최소',
    'checkin.slowest': '최대',
    'checkin.exportName': '출석 기록',
    'checkin.secondsUnit': '초',
    'checkin.minuteSecond': '{0}분{1}초',
    'seat.title': '좌석 배치',
    'seat.subtitle': '커스텀 레이아웃, 다양한 모드',
    'seat.rows': '행',
    'seat.cols': '열',
    'seat.groups': '그룹',
    'seat.skipRow': '행 건너뛰기',
    'seat.skipCol': '열 건너뛰기',
    'seat.startFrom': '시작',
    'seat.fromDoor': '문쪽부터',
    'seat.fromWindow': '창쪽부터',
    'seat.autoSeat': '자동 배치',
    'seat.colAisle': '열 통로',
    'seat.rowAisle': '행 통로',
    'seat.checkin': '출석',
    'seat.exportName': '좌석표',
    'seat.emptyTitle': '모드를 선택하고 「자동 배치」를 클릭',
    'seat.emptyDesc': '다양한 모드, 드래그로 교환',
    'seat.podium': '🏫 교단',
    'seat.window': '창문',
    'seat.door': '문',
    'seat.windowSide': '창문 쪽',
    'seat.doorSide': '문 쪽',
    'seat.swapDoorWindow': '문/창 교환',
    'seat.empty': '빈',
    'seat.legend': '💡 드래그로 교환 · 클릭으로 비활성화 · 더블클릭으로 통로 삭제',
    'seat.colLabel': '{0}열',
    'seat.rowLabel': '{0}행',
    'seatMode.verticalS': '세로 S형',
    'seatMode.horizontalS': '가로 S형',
    'seatMode.groupCol': '그룹/열',
    'seatMode.groupRow': '그룹/행',
    'seatMode.smartCluster': '스마트 클러스터',
    'seatMode.random': '랜덤',
    'seatMode.exam': '시험',
    'scene.classroom': '🏫 교실',
    'scene.classroomDesc': '그리드 배치',
    'scene.smartClassroom': '⭕ 스마트 교실',
    'scene.smartClassroomDesc': '원형 테이블',
    'scene.conference': '📋 회의실',
    'scene.conferenceDesc': '회의 테이블',
    'scene.concertHall': '🎵 콘서트홀',
    'scene.concertHallDesc': '반원형',
    'scene.banquet': '🎪 연회장',
    'scene.banquetDesc': '원형 테이블',
    'scene.computerLab': '💻 컴퓨터실',
    'scene.computerLabDesc': '긴 테이블 대면',
    'library.title': '학급 라이브러리',
    'library.import': '가져오기',
    'library.export': '내보내기',
    'library.addCollege': '학과 추가...',
    'library.addClass': '학급 추가...',
    'library.noColleges': '학과 없음',
    'library.noCollegesHint': '추가하거나 Excel 가져오기',
    'library.selectClass': '학급을 선택하세요',
    'library.loadToList': '명단에 로드',
    'library.studentNumber': '학번',
    'library.studentName': '이름',
    'library.confirmImport': '확인',
    'library.cancel': '취소',
    'library.importSuccess': '가져오기 성공',
    'library.importPreview': '미리보기',
    'library.college': '학과',
    'library.class': '학급',
    'library.append': '추가',
    'library.overwrite': '덮어쓰기',
    'library.existingClassHandling': '기존 학급:',
    'export.namePlaceholder': '내보내기 이름 ({0})',
    'export.exported': '{0}으로 내보냄',
    'export.failed': '내보내기 실패',
    'export.retry': '다시 시도하세요',
    'auth.appTitle': 'TeachMate',
    'auth.loginTitle': '로그인',
    'auth.signupTitle': '계정 만들기',
    'auth.forgotTitle': '비밀번호 재설정',
    'auth.emailPlaceholder': '이메일',
    'auth.passwordPlaceholder': '비밀번호',
    'auth.nicknamePlaceholder': '닉네임 (선택)',
    'auth.login': '로그인',
    'auth.signup': '가입',
    'auth.loginFailed': '로그인 실패',
    'auth.signupFailed': '가입 실패',
    'auth.signupSuccess': '가입 성공',
    'auth.signupSuccessDesc': '이메일을 확인하세요. 관리자 승인 후 전체 기능 사용 가능.',
    'auth.signupNote': '관리자 승인이 필요합니다',
    'auth.noAccount': '계정이 없으신가요? 가입',
    'auth.hasAccount': '계정이 있으신가요? 로그인',
    'auth.forgotPassword': '비밀번호 찾기',
    'auth.backToLogin': '로그인으로 돌아가기',
    'auth.sendReset': '재설정 이메일 보내기',
    'auth.sending': '전송 중...',
    'auth.pleaseWait': '잠시 기다려 주세요...',
    'auth.guestContinue': '게스트로 계속',
    'auth.pendingTitle': '승인 대기 중',
    'auth.pendingDesc': '계정이 승인 대기 중입니다.',
    'auth.pendingStatus': '대기 중',
    'auth.guestBtn': '게스트로 계속',
    'auth.rejectedTitle': '승인되지 않음',
    'auth.rejectedDesc': '신청이 승인되지 않았습니다. 관리자에게 문의하세요.',
    'reset.title': '새 비밀번호',
    'reset.placeholder': '새 비밀번호 (6자 이상)',
    'reset.confirm': '확인',
    'reset.resetting': '재설정 중...',
    'reset.invalidLink': '잘못된 링크',
    'reset.backToLogin': '로그인으로',
    'reset.minLength': '비밀번호는 6자 이상',
    'reset.failed': '재설정 실패',
    'reset.success': '비밀번호 재설정 완료',
    'admin.title': '사용자 관리',
    'admin.back': '뒤로',
    'admin.searchPlaceholder': '검색...',
    'admin.all': '전체',
    'admin.pending': '대기 중',
    'admin.approved': '승인됨',
    'admin.rejected': '거부됨',
    'admin.selected': '{0}명 선택',
    'admin.batchApprove': '일괄 승인',
    'admin.batchReject': '일괄 거부',
    'admin.approve': '승인',
    'admin.reject': '거부',
    'admin.changeToApprove': '승인으로 변경',
    'admin.selectAll': '전체 선택',
    'admin.noPending': '대기 중인 사용자 없음',
    'admin.operationFailed': '작업 실패',
    'admin.batchResult': '{1}명을 {0}',
    'checkinPage.loading': '로딩 중...',
    'checkinPage.expired': '출석 종료',
    'checkinPage.expiredDesc': '이 세션은 만료되었습니다',
    'checkinPage.success': '출석 완료!',
    'checkinPage.completed': '{0} 출석 완료',
    'checkinPage.title': '출석 확인',
    'checkinPage.desc': '이름을 입력하세요',
    'checkinPage.namePlaceholder': '이름 입력',
    'checkinPage.checkinBtn': '출석',
    'checkinPage.checking': '확인 중...',
    'checkinPage.failed': '실패했습니다. 다시 시도하세요.',
    'discuss.topicNotFound': '주제를 찾을 수 없습니다',
    'discuss.loading': '로딩 중...',
    'discuss.enterNickname': '닉네임으로 참여',
    'discuss.nicknamePlaceholder': '닉네임...',
    'discuss.enterDiscussion': '참여하기 🚀',
    'discuss.noRegister': '🔒 가입 불필요',
    'discuss.topic': '💬 토론 주제',
    'discuss.nickname': '닉네임',
    'discuss.edit': '수정',
    'discuss.recentBarrage': '최근 메시지',
    'discuss.inputBarrage': '메시지 입력 (최대 50자)...',
    'discuss.sendFailed': '전송 실패',
    'discuss.send': '보내기 🚀',
    'discuss.sendingBtn': '전송 중...',
    'discuss.sendSuccess': '✅ 전송 성공!',
    'discuss.dataPrivacy': '🔒 데이터는 교실 토론용',
    'notFound.title': '페이지를 찾을 수 없습니다',
    'notFound.back': '홈으로 돌아가기',
    'seatCheckin.title': '좌석 확인',
    'seatCheckin.desc': '이름을 입력하여 좌석 확인',
    'seatCheckin.namePlaceholder': '이름 입력',
    'seatCheckin.confirm': '확인',
    'seatCheckin.checking': '확인 중...',
    'seatCheckin.loading': '로딩 중...',
    'seatCheckin.notFound': '세션을 찾을 수 없습니다',
    'seatCheckin.success': '확인 완료!',
    'seatCheckinDialog.title': '좌석 확인',
    'seatCheckinDialog.desc': 'QR코드로 좌석 확인',
    'seatCheckinDialog.generate': 'QR코드 생성',
    'seatCheckinDialog.generating': '생성 중...',
    'seatCheckinDialog.checkedIn': '확인됨',
    'go.invalidLink': '잘못된 링크',
    'go.redirecting': '이동 중...',
    'go.openInBrowser': '브라우저에서 열기',
    'go.wechatWarning': 'WeChat 브라우저입니다. 브라우저에서 열어주세요.',
    'go.recommended': '추천',
    'go.recommendedDesc': '우측 상단 ⋯ → 「브라우저에서 열기」',
    'go.copyLink': '링크 복사',
    'go.copied': '복사됨!',
    'go.tryDirect': '직접 열기',
    'wechat.warning': 'WeChat 브라우저입니다. ⋯ → 「브라우저에서 열기」를 선택하세요.',
    'common.save': '저장',
    'common.cancel': '취소',
    'common.loading': '로딩 중...',
    'board.title': '크리에이티브 보드',
    'board.create': '보드 만들기',
    'board.myBoards': '내 보드',
    'board.noBoards': '보드가 없습니다',
    'board.emptyHint': '보드를 만들어 학생들이 카드로 아이디어를 공유하고 협업할 수 있게 하세요',
    'board.boardTitle': '보드 제목',
    'board.boardDesc': '설명 (선택)',
    'board.delete': '삭제',
    'board.deleteConfirm': '이 보드를 삭제하시겠습니까?',
    'board.settings': '설정',
    'board.lock': '잠금',
    'board.unlock': '잠금 해제',
    'board.locked': '잠김',
    'board.moderation': '검수',
    'board.moderationOn': '검수 활성화',
    'board.moderationOff': '검수 비활성화',
    'board.bannedWords': '금지어',
    'board.viewWall': '월',
    'board.viewKanban': '칸반',
    'board.viewTimeline': '타임라인',
    'board.viewCanvas': '캔버스',
    'board.addCard': '카드 추가',
    'board.cardContent': '내용 입력...',
    'board.cardColor': '카드 색상',
    'board.cardUrl': 'URL',
    'board.nickname': '닉네임',
    'board.nicknamePlaceholder': '닉네임 입력...',
    'board.submit': '게시',
    'board.submitting': '게시 중...',
    'board.submitSuccess': '게시되었습니다!',
    'board.submitPage': '카드 제출',
    'board.joinBoard': '참여',
    'board.scanToJoin': 'QR코드로 참여',
    'board.pin': '고정',
    'board.unpin': '고정 해제',
    'board.approve': '승인',
    'board.reject': '거부',
    'board.pending': '검토 중',
    'board.pendingCount': '{0} 건 검토 중',
    'board.likes': '좋아요',
    'board.comments': '댓글',
    'board.addComment': '댓글 추가...',
    'board.export': '내보내기',
    'board.exportCSV': 'CSV 내보내기',
    'board.exportPNG': '스크린샷',
    'board.pptMode': '슬라이드쇼',
    'board.wordCloud': '워드 클라우드',
    'board.wordCloudRefresh': '다시 생성',
    'board.wordCloudEmpty': '워드 클라우드를 생성할 콘텐츠가 부족합니다',
    'board.wordCloudTheme': '테마',
    'board.smartReport': '스마트 리포트',
    'board.reportGenerate': '리포트 생성',
    'board.reportGenerating': 'AI 분석 중...',
    'board.reportRegenerate': '다시 생성',
    'board.reportNoCards': '분석할 카드가 없습니다',
    'board.reportError': '리포트 생성 실패',
    'board.reportPrompt': '"리포트 생성"을 클릭하여 AI 분석을 시작하세요',
    'board.reportPromptSub': '{0}개 카드 내용을 분석합니다',
    'board.reportCardCount': '개 카드',
    'board.reportStreaming': '생성 중...',
    'ai.guestLimitReached': '오늘 AI 사용 횟수가 초과되었습니다. 로그인하면 무제한으로 사용할 수 있습니다',
    'ai.guestRemaining': '게스트 AI 사용: 오늘 {0}/{1}회 남음. 로그인하면 무제한',
    'board.pptPrev': '이전',
    'board.pptNext': '다음',
    'board.pptExit': '종료',
    'board.pptSlide': '{0} / {1}',
    'board.qrcode': 'QR코드',
    'board.shareLink': '공유 링크',
    'board.anonymous': '익명',
    'board.cardTypeText': '텍스트',
    'board.cardTypeImage': '이미지',
    'board.cardTypeUrl': '링크',
    'board.columns': '열',
    'board.addColumn': '열 추가',
    'board.blockedWord': '검토 대기 중',
    'board.lockedMsg': '보드가 잠겨 있습니다',
    'board.back': '보드 목록으로',
    'board.uploadImage': '이미지 업로드',
    'board.uploadFile': '파일 업로드',
    'board.uploading': '업로드 중...',
    'board.downloadFile': '다운로드',
    'board.viewFile': '파일 보기',
    'board.commentSend': '전송',
    'board.noComments': '댓글 없음',
    'board.cloudSync': '☁️ 클라우드 동기화됨',
  },
};

// Helper: replace {0}, {1}, etc. in translated strings
export function tFormat(template: string, ...args: (string | number)[]): string {
  return args.reduce<string>((str, arg, i) => str.replace(`{${i}}`, String(arg)), template);
}

interface LanguageContextValue {
  lang: LangCode;
  setLang: (lang: LangCode) => void;
  t: (key: string) => string;
}

const fallbackLanguageContext: LanguageContextValue = {
  lang: 'zh',
  setLang: () => {},
  t: (key: string) => translations.zh?.[key] ?? key,
};

const LanguageContext = createContext<LanguageContextValue>(fallbackLanguageContext);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<LangCode>(() => {
    const saved = localStorage.getItem('app-lang');
    return (saved as LangCode) || 'zh';
  });

  const setLang = useCallback((code: LangCode) => {
    setLangState(code);
    localStorage.setItem('app-lang', code);
  }, []);

  const t = useCallback((key: string) => {
    return translations[lang]?.[key] ?? translations['zh']?.[key] ?? key;
  }, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}

